-- =============================================================================
-- TESTE DO LOTE DO JOB 27 (whatsapp_reconcile_dispatch) — backpressure com
-- LIMIT de fila + janela de voo: o cron processa SEM empilhar e sem travar
-- (saturação do launcher pg_cron).
-- =============================================================================
-- Contexto (campanha 100 etapas, Onda G, wt-g13):
--   Job 27 `whatsapp_reconcile_dispatch` (cron: 0-59/5 * * * *,
--   `SELECT zapp.fn_reconcile_dispatch();`) falha ~13% por 'job startup
--   timeout' — saturação do scheduler pg_cron (211+ jobs ativos) agravada por
--   despacho INCONDICIONAL a cada 5 min: quando o apply (job 30) atrasa ou a
--   resposta pg_net expira, a fila evo.evolution_reconcile_jobs empilha sem
--   teto (1 request/5min = 288/dia) e cada run do apply fica mais pesado.
--
-- CONTRATO (fix wt-g13 — migration 20260817270000_fix_cron_27_...):
--   zapp.fn_reconcile_dispatch() passa a ter DOIS guards (antes do provider):
--     (1) LOTE LIMIT / backpressure: se há >= 5 jobs pendentes
--         (applied_at IS NULL) na fila → RAISE NOTICE + RETURN NULL (skip).
--         A fila tem TETO; o dispatch vira no-op barato quando o apply atrasa.
--     (2) JANELA / cooldown: se há request em voo (applied_at IS NULL e
--         dispatched_at > now()-interval '4 minutes') → skip. Com schedule
--         5 min, a fila nunca passa de ~1-2 em pipeline saudável.
--   Sem guards (estado atual de prod): despacha SEMPRE.
--
-- ESTADO RED ESPERADO (prod sem a migration): B1 e B2 falham (a fn atual
--   despacha mesmo com fila cheia/em voo). D1/B3/F1 passam (comportamento
--   pré-existente — regressão). Depois de aplicar a migration: GREEN total.
--
-- Como rodar (role postgres/supabase_admin):
--   psql "$SUPABASE_DB_URL" -f supabase/tests/test_job27_lote_limite.sql
--   (ou SQL editor / MCP). NÃO requer pg_net de teste — os guards rodam antes
--   do provider; só D1/B3 (caminho feliz) disparam 1 fetchInstances real cada
--   (benigno: o cron faria o mesmo em 5 min) e os jobs criados são removidos.
--
-- Higiene: DO block ÚNICO e atômico. Em FALHA → RAISE EXCEPTION → rollback
-- automático. Em SUCESSO → cleanup explícito no final (o MCP comita statement
-- que sucede — o cleanup por request_id/faixa namespaced é a garantia real).
-- Namespace de teste: request_ids 90000100..90000110 (nunca colidem com
-- request_ids reais, que são sequenciais baixos).
-- =============================================================================
DO $$
DECLARE
  v_failures text[] := '{}';
  v_seed_ts  timestamptz := now();
  v_ret      bigint;
  v_cnt_ant  int; v_cnt_dep int;
  v_intact   int;
  v_req_d1   bigint := NULL; v_req_b3 bigint := NULL;
  i          int;
BEGIN
  -- ─────────────────────────────────────────────────────────────
  -- SETUP (idempotente, namespaced)
  -- ─────────────────────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS evo.evolution_reconcile_jobs (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id    bigint NOT NULL UNIQUE,
    dispatched_at timestamptz NOT NULL DEFAULT now(),
    applied_at    timestamptz,
    http_status   integer,
    result        jsonb
  );
  -- Limpeza prévia da faixa de teste (defensivo p/ re-runs)
  DELETE FROM evo.evolution_reconcile_jobs
   WHERE request_id BETWEEN 90000100 AND 90000110;

  -- ─────────────────────────────────────────────────────────────
  -- TESTE B1: LOTE LIMIT (backpressure) — com 5 jobs pendentes a fn
  --           NÃO despacha: retorna NULL e a fila NÃO cresce.
  --           (RED agora: a fn atual despacha incondicionalmente)
  -- ─────────────────────────────────────────────────────────────
  BEGIN
    FOR i IN 1..5 LOOP
      INSERT INTO evo.evolution_reconcile_jobs (request_id, dispatched_at)
      VALUES (90000100 + i, v_seed_ts - interval '10 minutes' - (i || ' minutes')::interval);
    END LOOP;

    SELECT count(*) INTO v_cnt_ant FROM evo.evolution_reconcile_jobs
     WHERE request_id BETWEEN 90000100 AND 90000110;

    SELECT zapp.fn_reconcile_dispatch() INTO v_ret;

    SELECT count(*) INTO v_cnt_dep FROM evo.evolution_reconcile_jobs
     WHERE request_id BETWEEN 90000100 AND 90000110;

    IF v_ret IS NOT NULL THEN
      RAISE EXCEPTION 'B1: despachou com fila cheia (retorno %) — backpressure ausente', v_ret;
    END IF;
    IF v_cnt_dep <> v_cnt_ant THEN
      RAISE EXCEPTION 'B1: fila cresceu de % para % — teto de fila quebrado', v_cnt_ant, v_cnt_dep;
    END IF;
    RAISE NOTICE 'TEST B1 PASSED: backpressure — fila cheia não despacha (retorno NULL)';
  EXCEPTION WHEN OTHERS THEN
    v_failures := v_failures || format('B1: %s', SQLERRM);
  END;

  -- limpa os 5 de B1 p/ isolar o próximo teste
  DELETE FROM evo.evolution_reconcile_jobs
   WHERE request_id BETWEEN 90000100 AND 90000110;

  -- ─────────────────────────────────────────────────────────────
  -- TESTE B2: JANELA — com 1 request em voo (dispatched_at < 4min,
  --           applied_at NULL) a fn NÃO despacha.
  --           (RED agora: a fn atual despacha incondicionalmente)
  -- ─────────────────────────────────────────────────────────────
  BEGIN
    INSERT INTO evo.evolution_reconcile_jobs (request_id, dispatched_at)
    VALUES (90000101, v_seed_ts - interval '1 minute');

    SELECT count(*) INTO v_cnt_ant FROM evo.evolution_reconcile_jobs
     WHERE request_id BETWEEN 90000100 AND 90000110;

    SELECT zapp.fn_reconcile_dispatch() INTO v_ret;

    SELECT count(*) INTO v_cnt_dep FROM evo.evolution_reconcile_jobs
     WHERE request_id BETWEEN 90000100 AND 90000110;

    IF v_ret IS NOT NULL THEN
      RAISE EXCEPTION 'B2: despachou com request em voo (retorno %) — janela ausente', v_ret;
    END IF;
    IF v_cnt_dep <> v_cnt_ant THEN
      RAISE EXCEPTION 'B2: fila cresceu de % para % — cooldown quebrado', v_cnt_ant, v_cnt_dep;
    END IF;
    RAISE NOTICE 'TEST B2 PASSED: janela — request em voo não despacha (retorno NULL)';
  EXCEPTION WHEN OTHERS THEN
    v_failures := v_failures || format('B2: %s', SQLERRM);
  END;

  DELETE FROM evo.evolution_reconcile_jobs
   WHERE request_id BETWEEN 90000100 AND 90000110;

  -- ─────────────────────────────────────────────────────────────
  -- TESTE D1: anti-bloqueio — pendente ANTIGO (>4min) NÃO bloqueia a
  --           janela: a fn despacha (retorno NOT NULL) e enfileira 1.
  --           (pré-existente; protege contra janela virar bloqueio
  --           permanente por jobs antigos)
  -- ─────────────────────────────────────────────────────────────
  BEGIN
    INSERT INTO evo.evolution_reconcile_jobs (request_id, dispatched_at)
    VALUES (90000102, v_seed_ts - interval '10 minutes');

    SELECT zapp.fn_reconcile_dispatch() INTO v_ret;
    v_req_d1 := v_ret;

    IF v_ret IS NULL THEN
      RAISE EXCEPTION 'D1: pendente antigo bloqueou o dispatch (retorno NULL)';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM evo.evolution_reconcile_jobs WHERE request_id = v_ret) THEN
      RAISE EXCEPTION 'D1: despachou (%) mas não enfileirou', v_ret;
    END IF;
    RAISE NOTICE 'TEST D1 PASSED: pendente antigo não bloqueia (despachou %)', v_ret;
  EXCEPTION WHEN OTHERS THEN
    v_failures := v_failures || format('D1: %s', SQLERRM);
  END;

  -- remove o job real criado por D1 (request em voo atrapalharia o B3)
  IF v_req_d1 IS NOT NULL THEN
    DELETE FROM evo.evolution_reconcile_jobs WHERE request_id = v_req_d1;
  END IF;
  DELETE FROM evo.evolution_reconcile_jobs
   WHERE request_id BETWEEN 90000100 AND 90000110;

  -- ─────────────────────────────────────────────────────────────
  -- TESTE B3: fila saudável (vazia) → despacha e enfileira 1.
  --           (pré-existente; caminho feliz do cron)
  -- ─────────────────────────────────────────────────────────────
  BEGIN
    SELECT zapp.fn_reconcile_dispatch() INTO v_ret;
    v_req_b3 := v_ret;

    IF v_ret IS NULL THEN
      RAISE EXCEPTION 'B3: fila vazia não despachou (retorno NULL)';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM evo.evolution_reconcile_jobs WHERE request_id = v_ret) THEN
      RAISE EXCEPTION 'B3: despachou (%) mas não enfileirou', v_ret;
    END IF;
    RAISE NOTICE 'TEST B3 PASSED: fila saudável despacha e enfileira (%)', v_ret;
  EXCEPTION WHEN OTHERS THEN
    v_failures := v_failures || format('B3: %s', SQLERRM);
  END;

  -- ─────────────────────────────────────────────────────────────
  -- TESTE F1: controle — job de OUTRO contexto (90000110, já aplicado)
  --           nunca é tocado (nem deletado nem alterado).
  -- ─────────────────────────────────────────────────────────────
  BEGIN
    INSERT INTO evo.evolution_reconcile_jobs (request_id, dispatched_at, applied_at)
    VALUES (90000110, v_seed_ts - interval '1 hour', v_seed_ts - interval '30 minutes');

    SELECT count(*) INTO v_intact FROM evo.evolution_reconcile_jobs
     WHERE request_id = 90000110 AND applied_at = v_seed_ts - interval '30 minutes';

    IF v_intact <> 1 THEN
      RAISE EXCEPTION 'F1: job de outro contexto foi tocado (DELETE/UPDATE sem WHERE?)';
    END IF;
    RAISE NOTICE 'TEST F1 PASSED: job de outro contexto intacto';
  EXCEPTION WHEN OTHERS THEN
    v_failures := v_failures || format('F1: %s', SQLERRM);
  END;

  -- ─────────────────────────────────────────────────────────────
  -- CLEANUP EXPLÍCITO (sempre roda antes do veredicto — o MCP comita
  -- statement que sucede; em falha o rollback automático cobre)
  -- ─────────────────────────────────────────────────────────────
  DELETE FROM evo.evolution_reconcile_jobs
   WHERE request_id BETWEEN 90000100 AND 90000110;
  IF v_req_d1 IS NOT NULL THEN
    DELETE FROM evo.evolution_reconcile_jobs WHERE request_id = v_req_d1;
  END IF;
  IF v_req_b3 IS NOT NULL THEN
    DELETE FROM evo.evolution_reconcile_jobs WHERE request_id = v_req_b3;
  END IF;

  -- ─────────────────────────────────────────────────────────────
  -- VEREDICTO
  -- ─────────────────────────────────────────────────────────────
  IF array_length(v_failures, 1) IS NOT NULL THEN
    RAISE EXCEPTION '[job27_lote] FALHAS: %', array_to_string(v_failures, ' | ');
  END IF;
  RAISE NOTICE 'job27_lote: TODOS OS TESTES PASSARAM (job 27 com lote LIMIT + janela)';
END $$;
