import { createZappAdminClient } from '../_shared/db-client.ts';
import { getCorsHeaders, handleCorsPreflight } from '../_shared/cors.ts';
import { requireUser } from '../_shared/auth.ts';
import { checkRateLimit, isValidUUID } from '../_shared/validation.ts';
import { timingSafeStringEqual } from '../_shared/auth.ts';
import { parseOrReject, buildContractErrorBody } from '../_shared/contract-kit.ts';
import { GmailOauthV1Schema } from '../_shared/contract-schemas.ts';
import { getLogger } from '../_shared/logger.ts';
const log = getLogger('gmail-oauth');

/**
 * Signs an OAuth state token binding it to userId.
 * State = base64(userId|nonce|hmac) — prevents Account Binding CSRF.
 * Attacker cannot forge a state for another user without their JWT (needed for getAuthUrl).
 *
 * NÃO migrou pra _shared/hmac-validation.ts (PLANO-100 etapa 22, 2026-08-25):
 * é protocolo próprio de state token (chave DERIVADA via slice/padEnd + envelope
 * base64 userId|nonce|sigHex), não validação de assinatura de webhook — a API do
 * módulo (hex sobre body cru) mudaria a cripto e invalidaria states em trânsito.
 * A comparação já usa o comparador canônico timingSafeStringEqual (_shared/auth.ts).
 */
async function signOAuthState(userId: string, signingKey: string): Promise<string> {
  const nonce = crypto.randomUUID();
  const payload = `${userId}|${nonce}`;
  const keyMaterial = new TextEncoder().encode(signingKey.slice(0, 32).padEnd(32, '0'));
  const key = await crypto.subtle.importKey('raw', keyMaterial, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(payload));
  const sigHex = Array.from(new Uint8Array(sig)).map(b => b.toString(16).padStart(2, '0')).join('');
  return btoa(`${payload}|${sigHex}`);
}

/** Verifies state was generated by signOAuthState for userId. Returns false on any mismatch. */
async function verifyOAuthState(state: string, userId: string, signingKey: string): Promise<boolean> {
  try {
    const decoded = atob(state);
    const parts = decoded.split('|');
    if (parts.length !== 3) return false;
    const [stateUserId, nonce, sig] = parts;
    if (stateUserId !== userId) return false;
    const payload = `${stateUserId}|${nonce}`;
    const keyMaterial = new TextEncoder().encode(signingKey.slice(0, 32).padEnd(32, '0'));
    const key = await crypto.subtle.importKey('raw', keyMaterial, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
    const expected = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(payload));
    const expectedHex = Array.from(new Uint8Array(expected)).map(b => b.toString(16).padStart(2, '0')).join('');
    return timingSafeStringEqual(sig, expectedHex);
  } catch {
    return false;
  }
}

const GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token';
const GOOGLE_AUTH_URL  = 'https://accounts.google.com/o/oauth2/v2/auth';
const GOOGLE_USERINFO  = 'https://www.googleapis.com/oauth2/v2/userinfo';
const GOOGLE_REVOKE    = 'https://oauth2.googleapis.com/revoke';
const GMAIL_SCOPES = ['https://www.googleapis.com/auth/gmail.modify','https://www.googleapis.com/auth/gmail.send','https://www.googleapis.com/auth/gmail.compose','https://www.googleapis.com/auth/gmail.labels','https://www.googleapis.com/auth/userinfo.email','https://www.googleapis.com/auth/userinfo.profile'].join(' ');

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: getCorsHeaders(req) });
  const jsonHeaders = { ...getCorsHeaders(req), 'Content-Type': 'application/json' };

  /**
   * Falha de validação de campo obrigatório → envelope 422 ÚNICO (contract-kit).
   * Correção 2026-08-06 (gap A1-B6): era 400 {error} avulso.
   */
  const validation422 = (path: string, message: string, _req: Request, headers: Record<string, string>): Response =>
    new Response(JSON.stringify(buildContractErrorBody(
      'gmail-oauth', undefined, 'contract_violation',
      `Campo obrigatório ausente: ${path}.`,
      [{ path, message }],
    )), { status: 422, headers });

  const serviceRoleKey = (Deno.env.get('SELFHOSTED_SUPABASE_SERVICE_ROLE_KEY') ?? Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')) ?? '';
  const supabase = createZappAdminClient();
  const clientId = Deno.env.get('GOOGLE_CLIENT_ID') ?? '';
  const clientSecret = Deno.env.get('GOOGLE_CLIENT_SECRET') ?? '';
  const redirectUri = Deno.env.get('GMAIL_REDIRECT_URI') ?? `${(Deno.env.get('SELFHOSTED_SUPABASE_URL') ?? Deno.env.get('SUPABASE_URL'))}/functions/v1/gmail-oauth`;
  if (!serviceRoleKey || !clientId || !clientSecret) {
    return new Response(JSON.stringify({ error: 'Gmail OAuth not configured — set GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, and SUPABASE_SERVICE_ROLE_KEY in secrets.' }), { status: 503, headers: jsonHeaders });
  }
  try {
    // OAuth callback from Google \u2014 no auth header present, handled before auth check
    const url = new URL(req.url);
    if (req.method === 'GET' && url.searchParams.has('code')) {
      const code = url.searchParams.get('code')!;
      const state = url.searchParams.get('state');
      const errorP = url.searchParams.get('error');
      const safeJsonForScript = (value: unknown): string => JSON.stringify(value).replace(/</g, '\\u003c');
      if (errorP) return new Response(`<script>window.opener?.postMessage({type:'gmail-oauth-error',error:${safeJsonForScript(errorP)},state:${safeJsonForScript(state)}},'*');window.close()</script>`, { headers: { 'Content-Type': 'text/html' } });
      return new Response(`<script>\n          window.opener?.postMessage({type:'gmail-oauth-code',code:${safeJsonForScript(code)},state:${safeJsonForScript(state)}},'*');\n          window.close();\n        </script>`, { headers: { 'Content-Type': 'text/html' } });
    }

    // Auth ANTES do gate (validação Claude O2: não vazar metadado de contrato
    // para chamador não autenticado). Todas as actions exigem JWT.
    const authed = await requireUser(req);
    if (authed instanceof Response) return authed;
    const authenticatedUserId = authed.user.id;

    // Contrato gmail-oauth@v1 (estrito): action enum fechado (aliases kebab aceitos).
    const raw = await req.json().catch(() => null);
    const parsed = parseOrReject('gmail-oauth', { v1: GmailOauthV1Schema }, req, raw, {
      extraHeaders: jsonHeaders,
    });
    if (parsed.ok === false) return parsed.response;
    const body = parsed.data as Record<string, unknown>;
    const rawAction = body.action as string | undefined;
    const actionMap: Record<string, string> = { 'get-auth-url': 'getAuthUrl', 'exchange-code': 'exchangeCode', 'refresh-token': 'refresh', 'disconnect': 'revoke', 'list-accounts': 'listAccounts' };
    const action = rawAction && actionMap[rawAction] ? actionMap[rawAction] : rawAction;

    const rl = checkRateLimit(`gmail-oauth:${authenticatedUserId}`, 20, 60_000);
    if (!rl.allowed) return new Response(JSON.stringify({ error: 'Rate limit exceeded' }), { status: 429, headers: jsonHeaders });

    // State token is HMAC-signed with userId \u2014 prevents Account Binding CSRF
    if (action === 'getAuthUrl') {
      const state = await signOAuthState(authenticatedUserId, serviceRoleKey);
      const params = new URLSearchParams({ client_id: clientId, redirect_uri: redirectUri, response_type: 'code', scope: GMAIL_SCOPES, access_type: 'offline', prompt: 'consent', state });
      return new Response(JSON.stringify({ url: `${GOOGLE_AUTH_URL}?${params}`, state }), { headers: jsonHeaders });
    }

    if (action === 'exchangeCode') {
      const { code, userId, state } = body as Record<string, any>;
      if (!code || !userId) return validation422('code,userId', 'code e userId obrigat\u00f3rios', req, jsonHeaders);
      // Prevent token hijacking: caller may only bind the OAuth code to their own account
      if (userId !== authenticatedUserId) return new Response(JSON.stringify({ error: 'Forbidden: userId does not match authenticated user' }), { status: 403, headers: jsonHeaders });
      // Verify HMAC-signed state \u2014 prevents Account Binding CSRF
      if (!state || !await verifyOAuthState(state, authenticatedUserId, serviceRoleKey)) return new Response(JSON.stringify({ error: 'Invalid or missing OAuth state' }), { status: 403, headers: jsonHeaders });
      const tokenRes = await fetch(GOOGLE_TOKEN_URL, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ code, client_id: clientId, client_secret: clientSecret, redirect_uri: redirectUri, grant_type: 'authorization_code' }), signal: AbortSignal.timeout(10_000) });
      if (!tokenRes.ok) return new Response(JSON.stringify({ error: `Google token exchange failed: ${tokenRes.status}` }), { status: 502, headers: jsonHeaders });
      const tokens = await tokenRes.json();
      if (tokens.error) return new Response(JSON.stringify({ error: tokens.error_description ?? tokens.error }), { status: 400, headers: jsonHeaders });
      const profileRes = await fetch(GOOGLE_USERINFO, { headers: { Authorization: `Bearer ${tokens.access_token}` }, signal: AbortSignal.timeout(10_000) });
      if (!profileRes.ok) return new Response(JSON.stringify({ error: `Google userinfo failed: ${profileRes.status}` }), { status: 502, headers: jsonHeaders });
      const profile = await profileRes.json();
      const expiresAt = new Date(Date.now() + (tokens.expires_in ?? 3600) * 1000).toISOString();
      const { data: account, error: upsertErr } = await supabase.from('gmail_accounts').upsert({ user_id: authenticatedUserId, email: profile.email, display_name: profile.name, picture_url: profile.picture, access_token: tokens.access_token, refresh_token: tokens.refresh_token, token_expiry: expiresAt, scope: tokens.scope, is_active: true }, { onConflict: 'user_id,email' }).select('id, email').single();
      if (upsertErr) { log.error('account upsert failed', { error: upsertErr.message }); return new Response(JSON.stringify({ error: "Internal server error" }), { status: 500, headers: jsonHeaders }); }
      return new Response(JSON.stringify({ success: true, accountId: account.id, email: account.email }), { headers: jsonHeaders });
    }
    if (action === 'refresh') {
      const { accountId } = body;
      if (!accountId) return validation422('accountId', 'accountId obrigat\u00f3rio', req, jsonHeaders);
      const { data: account, error: fetchErr } = await supabase.from('gmail_accounts').select('refresh_token, user_id').eq('id', accountId).single();
      if (fetchErr || !account) return new Response(JSON.stringify({ error: 'Conta n\u00e3o encontrada' }), { status: 404, headers: jsonHeaders });
      // Verify caller owns this account
      if (account.user_id !== authenticatedUserId) return new Response(JSON.stringify({ error: 'Forbidden' }), { status: 403, headers: jsonHeaders });
      const tokenRes = await fetch(GOOGLE_TOKEN_URL, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ refresh_token: account.refresh_token, client_id: clientId, client_secret: clientSecret, grant_type: 'refresh_token' }), signal: AbortSignal.timeout(10_000) });
      if (!tokenRes.ok && tokenRes.status !== 400) return new Response(JSON.stringify({ error: `Google token refresh failed: ${tokenRes.status}` }), { status: 502, headers: jsonHeaders });
      const tokens = await tokenRes.json();
      if (tokens.error) {
        const PERMANENT_ERRORS = ['invalid_grant', 'token_revoked'];
        const isPermanent = typeof tokens.error === 'string' && PERMANENT_ERRORS.includes(tokens.error);
        if (isPermanent) {
          const { error: deactivateErr } = await supabase.from('gmail_accounts').update({ is_active: false }).eq('id', accountId);
          if (deactivateErr) log.warn('deactivate account failed', { error: deactivateErr.message });
        }
        const msg = isPermanent ? 'refresh_token inv\u00e1lido \u2014 reconecte a conta' : `Google token error: ${tokens.error}`;
        return new Response(JSON.stringify({ error: msg }), { status: isPermanent ? 401 : 502, headers: jsonHeaders });
      }
      const expiresAt = new Date(Date.now() + (tokens.expires_in ?? 3600) * 1000).toISOString();
      const { error: tokenUpdateErr } = await supabase.from('gmail_accounts').update({ access_token: tokens.access_token, token_expiry: expiresAt, ...(tokens.refresh_token ? { refresh_token: tokens.refresh_token } : {}) }).eq('id', accountId);
      if (tokenUpdateErr) log.warn('token update failed', { error: tokenUpdateErr.message });
      return new Response(JSON.stringify({ access_token: tokens.access_token, token_expiry: expiresAt }), { headers: jsonHeaders });
    }
    if (action === 'revoke') {
      const { accountId } = body;
      if (!accountId) return validation422('accountId', 'accountId obrigat\u00f3rio', req, jsonHeaders);
      const { data: account } = await supabase.from('gmail_accounts').select('access_token, user_id').eq('id', accountId).single();
      // Verify caller owns this account before deleting
      if (!account || account.user_id !== authenticatedUserId) return new Response(JSON.stringify({ error: 'Forbidden' }), { status: 403, headers: jsonHeaders });
      if (account.access_token) {
        try { await fetch(GOOGLE_REVOKE, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ token: account.access_token }), signal: AbortSignal.timeout(10_000) }); }
        catch (revokeErr) { log.warn('Google revoke failed (continuing with DB deletion)', { error: revokeErr instanceof Error ? revokeErr.message : String(revokeErr) }); }
      }
      const { error: deleteAccErr } = await supabase.from('gmail_accounts').delete().eq('id', accountId);
      if (deleteAccErr) log.warn('account delete failed', { error: deleteAccErr.message });
      return new Response(JSON.stringify({ success: true }), { headers: { ...getCorsHeaders(req), 'Content-Type': 'application/json' } });
    }
    return new Response(JSON.stringify({ error: 'A\u00e7\u00e3o desconhecida' }), { status: 400, headers: jsonHeaders });
  } catch (err) {
    log.error('unhandled error', { error: err instanceof Error ? err.message : String(err) });
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500, headers: jsonHeaders });
  }
});