import type { ConversationWithMessages, RealtimeMessage } from '@/features/inbox/hooks/useRealtimeMessages';

// Extensão do tipo para compatibilidade com useRealtimeMessages e o componente ConversationItem legado
export interface MockConversationWithMessages extends ConversationWithMessages {
  id: string;
  status: 'open' | 'pending' | 'resolved' | 'waiting';
  priority: 'high' | 'medium' | 'low';
  updatedAt: Date; // Usado pelo formatDistanceToNow
  tags: string[];
}

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000);
const hoursAgo = (h: number) => new Date(now - h * 60 * 60_000);
const daysAgo = (d: number) => new Date(now - d * 24 * 60 * 60_000);

const createMockMessage = (id: string, contactId: string, content: string, sender: 'contact' | 'agent', timestamp: Date): RealtimeMessage => ({
  id,
  contact_id: contactId,
  agent_id: sender === 'agent' ? 'agent-1' : null,
  content,
  sender,
  message_type: 'text',
  media_url: null,
  is_read: true,
  status: 'read',
  status_updated_at: timestamp.toISOString(),
  created_at: timestamp.toISOString(),
  updated_at: timestamp.toISOString(),
  external_id: `ext-${id}`,
  whatsapp_connection_id: 'conn-1',
  transcription: null,
  transcription_status: null,
  is_deleted: false
});

export const MOCK_CONVERSATIONS: any[] = [
  {
    id: 'mock-1',
    status: 'open',
    priority: 'high',
    unreadCount: 7,
    tags: ['vip', 'enterprise'],
    updatedAt: minutesAgo(2),
    contact: {
      id: 'mock-contact-1',
      name: 'Maria Eduarda Souza Oliveira',
      company: 'Acme Corporation Ltda.',
      phone: '5511988887777',
      tags: ['vip', 'enterprise', 'renovação', 'q2-2026'],
      created_at: daysAgo(120).toISOString(),
      updated_at: minutesAgo(2).toISOString(),
      contact_type: 'whatsapp',
      avatar_url: 'https://i.pravatar.cc/150?img=47',
    },
    lastMessage: createMockMessage('m1', 'mock-contact-1', 'Bom dia! Recebi a proposta atualizada e gostaria de agendar uma call.', 'contact', minutesAgo(2)),
    messages: []
  },
  {
    id: 'mock-2',
    status: 'pending',
    priority: 'medium',
    unreadCount: 0,
    tags: ['lead'],
    updatedAt: minutesAgo(15),
    contact: {
      id: 'mock-contact-2',
      name: 'João Silva',
      company: 'Tech Solutions',
      phone: '5511977776666',
      tags: ['lead'],
      created_at: daysAgo(30).toISOString(),
      updated_at: minutesAgo(15).toISOString(),
      contact_type: 'whatsapp',
    },
    lastMessage: createMockMessage('m2', 'mock-contact-2', 'Perfeito, obrigado!', 'contact', minutesAgo(15)),
    messages: []
  },
  {
    id: 'mock-3',
    status: 'open',
    priority: 'low',
    unreadCount: 3,
    tags: ['suporte'],
    updatedAt: minutesAgo(45),
    contact: {
      id: 'mock-contact-3',
      name: 'Ana Carolina',
      company: null,
      phone: '5511966665555',
      tags: ['suporte', 'bug-report'],
      created_at: daysAgo(15).toISOString(),
      updated_at: minutesAgo(45).toISOString(),
      contact_type: 'instagram',
      ai_sentiment: 'negative'
    },
    lastMessage: createMockMessage('m3', 'mock-contact-3', 'Continua sem funcionar 😡', 'contact', minutesAgo(45)),
    messages: []
  },
  {
    id: 'mock-4',
    status: 'waiting',
    priority: 'medium',
    unreadCount: 0,
    tags: [],
    updatedAt: hoursAgo(2),
    contact: {
      id: 'mock-contact-4',
      name: '',
      company: 'PromoGifts & Brindes',
      phone: '5511955554444',
      tags: [],
      created_at: daysAgo(60).toISOString(),
      updated_at: hoursAgo(2).toISOString(),
      contact_type: 'email',
    },
    lastMessage: null,
    messages: []
  },
  {
    id: 'mock-5',
    status: 'open',
    priority: 'high',
    unreadCount: 12,
    tags: ['urgente'],
    updatedAt: minutesAgo(1),
    contact: {
      id: 'mock-contact-5',
      name: 'Roberto Carlos Pereira da Silva Neto',
      company: 'Multinacional Internacional Brasil S/A',
      phone: '5511944443333',
      tags: ['urgente', 'churn-risk', 'c-level'],
      created_at: daysAgo(200).toISOString(),
      updated_at: minutesAgo(1).toISOString(),
      contact_type: 'whatsapp',
      avatar_url: 'https://i.pravatar.cc/150?img=33',
      ai_sentiment: 'negative'
    },
    lastMessage: createMockMessage('m5', 'mock-contact-5', 'Preciso de uma resposta URGENTE sobre o cancelamento do contrato.', 'contact', minutesAgo(1)),
    messages: []
  },
  {
    id: 'mock-6',
    status: 'resolved',
    priority: 'low',
    unreadCount: 0,
    tags: ['parceiro'],
    updatedAt: hoursAgo(8),
    contact: {
      id: 'mock-contact-6',
      name: 'Carla Mendes',
      company: 'Sicoob',
      phone: '5511933332222',
      tags: ['parceiro'],
      created_at: daysAgo(90).toISOString(),
      updated_at: hoursAgo(8).toISOString(),
      contact_type: 'sicoob_gifts',
      avatar_url: 'https://i.pravatar.cc/150?img=23',
      ai_sentiment: 'positive'
    },
    lastMessage: createMockMessage('m6', 'mock-contact-6', 'Ok, resolvido! Valeu pelo suporte 🙏', 'contact', hoursAgo(8)),
    messages: []
  },
  {
    id: 'mock-7',
    status: 'pending',
    priority: 'medium',
    unreadCount: 1,
    tags: ['demo'],
    updatedAt: hoursAgo(3),
    contact: {
      id: 'mock-contact-7',
      name: 'Fernanda Lima',
      company: 'Bitrix24 BR',
      phone: '5511922221111',
      tags: ['integração-crm', 'demo-agendada'],
      created_at: daysAgo(45).toISOString(),
      updated_at: hoursAgo(3).toISOString(),
      contact_type: 'phone',
    },
    lastMessage: createMockMessage('m7', 'mock-contact-7', 'Pode me ligar amanhã às 10h?', 'agent', hoursAgo(3)),
    messages: []
  },
  {
    id: 'mock-8',
    status: 'open',
    priority: 'low',
    unreadCount: 0,
    tags: [],
    updatedAt: daysAgo(1),
    contact: {
      id: 'mock-contact-8',
      name: 'Pedro Henrique',
      company: null,
      phone: '5511911110000',
      tags: [],
      created_at: daysAgo(20).toISOString(),
      updated_at: daysAgo(1).toISOString(),
      contact_type: 'whatsapp',
    },
    lastMessage: createMockMessage('m8', 'mock-contact-8', '👍', 'contact', daysAgo(1)),
    messages: []
  },
  {
    id: 'mock-9',
    status: 'open',
    priority: 'high',
    unreadCount: 4,
    tags: ['vip'],
    updatedAt: minutesAgo(8),
    contact: {
      id: 'mock-contact-9',
      name: 'Juliana Ribeiro',
      company: 'Boutique Atelier',
      phone: '5511900008888',
      tags: ['vip', 'fidelidade'],
      created_at: daysAgo(80).toISOString(),
      updated_at: minutesAgo(8).toISOString(),
      contact_type: 'instagram',
      channel_type: 'instagram',
      avatar_url: 'https://i.pravatar.cc/150?img=49',
      ai_sentiment: 'positive',
    },
    lastMessage: createMockMessage('m9', 'mock-contact-9', 'Adorei a coleção nova! Quando chegam as peças tamanho M?', 'contact', minutesAgo(8)),
    messages: []
  },
  {
    id: 'mock-10',
    status: 'open',
    priority: 'medium',
    unreadCount: 2,
    tags: ['suporte', 'webchat'],
    updatedAt: minutesAgo(22),
    contact: {
      id: 'mock-contact-10',
      name: 'Lucas Almeida',
      company: 'Startup XYZ',
      phone: '5511899997777',
      tags: ['suporte'],
      created_at: daysAgo(10).toISOString(),
      updated_at: minutesAgo(22).toISOString(),
      contact_type: 'webchat',
      channel_type: 'chat',
      avatar_url: 'https://i.pravatar.cc/150?img=12',
    },
    lastMessage: createMockMessage('m10', 'mock-contact-10', 'Olá, vim pelo site. Vocês têm plano para times pequenos?', 'contact', minutesAgo(22)),
    messages: []
  },
  {
    id: 'mock-11',
    status: 'open',
    priority: 'low',
    unreadCount: 0,
    tags: ['fornecedor'],
    updatedAt: hoursAgo(1),
    contact: {
      id: 'mock-contact-11',
      name: 'Distribuidora ABC',
      company: 'ABC Logística',
      phone: '5511888886666',
      tags: ['fornecedor', 'cotacao'],
      created_at: daysAgo(150).toISOString(),
      updated_at: hoursAgo(1).toISOString(),
      contact_type: 'whatsapp',
      channel_type: 'whatsapp',
      avatar_url: 'https://i.pravatar.cc/150?img=68',
    },
    lastMessage: createMockMessage('m11', 'mock-contact-11', 'Cotação enviada por e-mail, conforme combinado.', 'agent', hoursAgo(1)),
    messages: []
  },
  {
    id: 'mock-12',
    status: 'resolved',
    priority: 'medium',
    unreadCount: 0,
    tags: [],
    updatedAt: daysAgo(2),
    contact: {
      id: 'mock-contact-12',
      name: 'Beatriz Costa',
      company: 'Freelancer',
      phone: '5511877775555',
      tags: ['cliente-final'],
      created_at: daysAgo(60).toISOString(),
      updated_at: daysAgo(2).toISOString(),
      contact_type: 'whatsapp',
      channel_type: 'whatsapp',
      avatar_url: 'https://i.pravatar.cc/150?img=44',
      ai_sentiment: 'positive',
    },
    lastMessage: createMockMessage('m12', 'mock-contact-12', 'Tudo certo! Obrigada pelo atendimento ⭐⭐⭐⭐⭐', 'contact', daysAgo(2)),
    messages: []
  },
  {
    id: 'mock-13',
    status: 'pending',
    priority: 'high',
    unreadCount: 5,
    tags: ['churn-risk'],
    updatedAt: minutesAgo(35),
    contact: {
      id: 'mock-contact-13',
      name: 'Eduardo Martins',
      company: 'Construtora Solaris',
      phone: '5511866664444',
      tags: ['churn-risk', 'enterprise', 'renovacao-pendente'],
      created_at: daysAgo(365).toISOString(),
      updated_at: minutesAgo(35).toISOString(),
      contact_type: 'whatsapp',
      channel_type: 'whatsapp',
      avatar_url: 'https://i.pravatar.cc/150?img=15',
      ai_sentiment: 'negative',
    },
    lastMessage: createMockMessage('m13', 'mock-contact-13', 'Preciso urgentemente revisar os valores do contrato antes de renovar.', 'contact', minutesAgo(35)),
    messages: []
  },
  {
    id: 'mock-14',
    status: 'open',
    priority: 'low',
    unreadCount: 1,
    tags: ['novo-lead'],
    updatedAt: hoursAgo(5),
    contact: {
      id: 'mock-contact-14',
      name: 'Patrícia Nogueira',
      company: null,
      phone: '5511855553333',
      tags: ['novo-lead', 'inbound'],
      created_at: daysAgo(2).toISOString(),
      updated_at: hoursAgo(5).toISOString(),
      contact_type: 'instagram',
      channel_type: 'instagram',
      avatar_url: 'https://i.pravatar.cc/150?img=25',
    },
    lastMessage: createMockMessage('m14', 'mock-contact-14', 'Vi vocês no Insta, queria saber mais sobre como funciona!', 'contact', hoursAgo(5)),
    messages: []
  },
  {
    id: 'mock-15',
    status: 'open',
    priority: 'medium',
    unreadCount: 0,
    tags: ['parceiro'],
    updatedAt: minutesAgo(50),
    contact: {
      id: 'mock-contact-15',
      name: 'Rafael Vieira',
      company: 'Agência Pixel',
      phone: '5511844442222',
      tags: ['parceiro', 'co-marketing'],
      created_at: daysAgo(100).toISOString(),
      updated_at: minutesAgo(50).toISOString(),
      contact_type: 'whatsapp',
      channel_type: 'whatsapp',
      avatar_url: 'https://i.pravatar.cc/150?img=58',
    },
    lastMessage: createMockMessage('m15', 'mock-contact-15', 'Bora alinhar a campanha conjunta semana que vem?', 'agent', minutesAgo(50)),
    messages: []
  },
];
