// @ts-nocheck
import { useEffect, useState, useCallback, useRef, lazy, Suspense } from 'react';
import { useAuth } from '@/features/auth';
import { useIsMobile } from '@/hooks/use-mobile';
import { usePullToRefresh } from '@/hooks/usePullToRefresh';
import { MiniChatPiP } from '@/components/mobile/MiniChatPiP';
import { NewMessageIndicator } from './NewMessageIndicator';
import { MessageBatcherIndicator } from './MessageBatcherIndicator';
import { InboxEmptyChat } from './InboxEmptyChat';
import { SectionErrorBoundary } from '@/components/ui/section-error-boundary';
import { ConversationListSidebar } from './ConversationListSidebar';
import { useGlobalSearchShortcut } from '@/hooks/useGlobalSearchShortcut';
import { useInboxBulkActions } from '@/features/inbox';
import { useInboxFilters } from '@/features/inbox';
import { useRealtimeInbox } from '@/features/inbox';
import { useRealtimeContacts } from '@/features/inbox';
import { useRealtimeFallbackRefetch } from '@/features/inbox';
import { useSLAAlerts } from '@/features/sla';
import { useDepartmentAgents } from '@/features/auth';
import { useEvolutionAutoReconnect } from '@/hooks/useEvolutionAutoReconnect';
import { useAriaAnnouncer } from '@/hooks/useAriaAnnouncer';
import { isValidUUID } from '@/utils/uuid';
import { WifiOff, RefreshCw, Loader2, MessageSquarePlus } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { Button } from '@/components/ui/button';
