import { lazyWithRetry } from '@/lib/lazyWithRetry';
import React from 'react';

// Lazy-loaded views with automatic retry (3 attempts with backoff)
export const RealtimeInboxView = lazyWithRetry(() => import('@/features/inbox').then(m => ({ default: m.RealtimeInboxView })));
export const DashboardView = lazyWithRetry(() => import('@/components/dashboard/DashboardView').then(m => ({ default: m.DashboardView })));
export const SentimentAlertsDashboard = lazyWithRetry(() => import('@/components/dashboard/SentimentAlertsDashboard').then(m => ({ default: m.SentimentAlertsDashboard })));
export const AgentsView = lazyWithRetry(() => import('@/components/agents/AgentsView').then(m => ({ default: m.AgentsView })));
export const QueuesView = lazyWithRetry(() => import('@/components/queues/QueuesView').then(m => ({ default: m.QueuesView })));
export const ContactsView = lazyWithRetry(() => import('@/components/contacts/ContactsView').then(m => ({ default: m.ContactsView })));
export const ConnectionsView = lazyWithRetry(() => import('@/components/connections/ConnectionsView').then(m => ({ default: m.ConnectionsView })));
export const TagsView = lazyWithRetry(() => import('@/components/tags/TagsView').then(m => ({ default: m.TagsView })));
export const SettingsView = lazyWithRetry(() => import('@/components/settings/SettingsView').then(m => ({ default: m.SettingsView })));
export const ClientWalletView = lazyWithRetry(() => import('@/components/wallet/ClientWalletView').then(m => ({ default: m.ClientWalletView })));
export const AdminView = lazyWithRetry(() => import('@/features/admin').then(m => ({ default: m.AdminView })));
export const ProductManagement = lazyWithRetry(() => import('@/components/catalog/ExternalProductManagement').then(m => ({ default: m.ExternalProductManagement })));
export const GroupsView = lazyWithRetry(() => import('@/components/groups/GroupsView').then(m => ({ default: m.GroupsView })));
export const TranscriptionsHistoryView = lazyWithRetry(() => import('@/components/transcriptions/TranscriptionsHistoryView').then(m => ({ default: m.TranscriptionsHistoryView })));
export const AdvancedReportsView = lazyWithRetry(() => import('@/components/reports/AdvancedReportsView').then(m => ({ default: m.AdvancedReportsView })));
export const SecurityView = lazyWithRetry(() => import('@/components/security/SecurityView').then(m => ({ default: m.SecurityView })));
export const SystemFeaturesView = lazyWithRetry(() => import('@/components/docs/SystemFeaturesView').then(m => ({ default: m.SystemFeaturesView })));
export const CampaignsView = lazyWithRetry(() => import('@/components/campaigns/CampaignsView').then(m => ({ default: m.CampaignsView })));
export const ChatbotFlowsView = lazyWithRetry(() => import('@/components/chatbot/ChatbotFlowsView').then(m => ({ default: m.ChatbotFlowsView })));
export const AutomationsManager = lazyWithRetry(() => import('@/components/automations/AutomationsManager').then(m => ({ default: m.AutomationsManager })));
export const IntegrationsHub = lazyWithRetry(() => import('@/components/integrations/IntegrationsHub').then(m => ({ default: m.IntegrationsHub })));
export const LGPDComplianceView = lazyWithRetry(() => import('@/components/compliance/LGPDComplianceView').then(m => ({ default: m.LGPDComplianceView })));
export const SalesPipelineView = lazyWithRetry(() => import('@/components/pipeline/SalesPipelineView').then(m => ({ default: m.SalesPipelineView })));
export const KnowledgeBaseView = lazyWithRetry(() => import('@/components/knowledge/KnowledgeBaseView').then(m => ({ default: m.KnowledgeBaseView })));
export const PaymentLinksView = lazyWithRetry(() => import('@/components/payments/PaymentLinksView').then(m => ({ default: m.PaymentLinksView })));
export const WhatsAppFlowsBuilder = lazyWithRetry(() => import('@/components/whatsapp-flows/WhatsAppFlowsBuilder').then(m => ({ default: m.WhatsAppFlowsBuilder })));
export const MetaCAPIView = lazyWithRetry(() => import('@/components/meta-capi/MetaCAPIView').then(m => ({ default: m.MetaCAPIView })));
export const DiagnosticsView = lazyWithRetry(() => import('@/components/diagnostics/DiagnosticsView').then(m => ({ default: m.DiagnosticsView })));
export const VoIPPanel = lazyWithRetry(() => import('@/components/calls/VoIPPanel').then(m => ({ default: m.VoIPPanel })));
export const AutoExportManager = lazyWithRetry(() => import('@/components/reports/AutoExportManager').then(m => ({ default: m.AutoExportManager })));
export const GoogleCalendarIntegration = lazyWithRetry(() => import('@/components/integrations/GoogleCalendarIntegration').then(m => ({ default: m.GoogleCalendarIntegration })));
export const ThemeCustomizer = lazyWithRetry(() => import('@/components/settings/ThemeCustomizer').then(m => ({ default: m.ThemeCustomizer })));
export const ScheduleCalendarView = lazyWithRetry(() => import('@/components/schedule/ScheduleCalendarView').then(m => ({ default: m.ScheduleCalendarView })));
export const WarRoomDashboard = lazyWithRetry(() => import('@/components/dashboard/WarRoomDashboard').then(m => ({ default: m.WarRoomDashboard })));
export const WhatsAppTemplatesManager = lazyWithRetry(() => import('@/components/catalog/WhatsAppTemplatesManager').then(m => ({ default: m.WhatsAppTemplatesManager })));
export const OmnichannelManager = lazyWithRetry(() => import('@/components/omnichannel/OmnichannelManager').then(m => ({ default: m.OmnichannelManager })));
export const ChurnPredictionDashboard = lazyWithRetry(() => import('@/components/ai/ChurnPredictionDashboard').then(m => ({ default: m.ChurnPredictionDashboard })));
export const AutoTicketClassifier = lazyWithRetry(() => import('@/components/ai/AutoTicketClassifier').then(m => ({ default: m.AutoTicketClassifier })));
export const PerformanceMonitor = lazyWithRetry(() => import('@/components/performance/PerformanceMonitor').then(m => ({ default: m.PerformanceMonitor })));
export const OmnichannelInbox = lazyWithRetry(() => import('@/components/omnichannel/OmnichannelInbox').then(m => ({ default: m.OmnichannelInbox })));
export const AuditLogDashboard = lazyWithRetry(() => import('@/components/security/AuditLogDashboard').then(m => ({ default: m.AuditLogDashboard })));
export const AdminTelemetriaPage = lazyWithRetry(() => import('@/pages/AdminTelemetriaPage'));
export const AdminFailedMessagesPage = lazyWithRetry(() => import('@/pages/AdminFailedMessagesPage'));
export const AdminFailedAuthMessagesPage = lazyWithRetry(() => import('@/pages/admin/AdminFailedAuthMessagesPage'));
export const AdminSearchInsightsPage = lazyWithRetry(() => import('@/pages/AdminSearchInsightsPage'));
export const AdminWebhookEventsPage = lazyWithRetry(() => import('@/pages/AdminWebhookEventsPage'));
export const AdminEvolutionApiLogsPage = lazyWithRetry(() => import('@/pages/AdminEvolutionApiLogsPage'));
export const AdminAlertHistoryPage = lazyWithRetry(() => import('@/pages/AdminAlertHistoryPage'));
export const AdminWebhookOverviewPage = lazyWithRetry(() => import('@/pages/AdminWebhookOverviewPage'));
export const NPSDashboard = lazyWithRetry(() => import('@/components/nps/NPSDashboard').then(m => ({ default: m.NPSDashboard })));
export const SLADashboardView = lazyWithRetry(() => import('@/components/queues/SLADashboard').then(m => ({ default: m.SLADashboard })));
export const TeamChatView = lazyWithRetry(() => import('@/components/team-chat/TeamChatView').then(m => ({ default: m.TeamChatView })));
export const GmailInboxView = lazyWithRetry(() => import('@/components/gmail/GmailInboxView'));
export const EmailChatView = lazyWithRetry(() => import('@/components/email/EmailChatInbox').then(m => ({ default: m.EmailChatInbox })));
export const PublicApiDashboard = lazyWithRetry(() => import('@/features/admin').then(m => ({ default: m.PublicApiDashboard })));
export const GmailWebhookMonitor = lazyWithRetry(() => import('@/features/admin').then(m => ({ default: m.GmailWebhookMonitor })));
export const MediaMigrationTool = lazyWithRetry(() => import('@/features/admin').then(m => ({ default: m.MediaMigrationTool })));
export const SicoobBridgeDashboard = lazyWithRetry(() => import('@/features/admin').then(m => ({ default: m.SicoobBridgeDashboard })));
export const CRM360ExplorerView = lazyWithRetry(() => import('@/components/crm360/CRM360ExplorerView').then(m => ({ default: m.CRM360ExplorerView })));
export const AIUsageDashboard = lazyWithRetry(() => import('@/features/admin').then(m => ({ default: m.AIUsageDashboard })));
export const TalkXView = lazyWithRetry(() => import('@/components/talkx/TalkXView'));
export const EvolutionMonitoringDashboard = lazyWithRetry(() => import('@/components/monitoring/EvolutionMonitoringDashboard').then(m => ({ default: m.EvolutionMonitoringDashboard })));
export const AdminWebhookSecretStatusPage = lazyWithRetry(() => import('@/pages/AdminWebhookSecretStatusPage'));
export const AdminInstancePausesPage = lazyWithRetry(() => import('@/pages/AdminInstancePausesPage'));
export const AgentsOperationsPage = lazyWithRetry(() => import('@/pages/inbox/AgentsOperationsPage'));
export const AdminRealtimeMonitorPage = lazyWithRetry(() => import('@/pages/AdminRealtimeMonitorPage'));
export const AdminDispatchErrorsHistoryPage = lazyWithRetry(() => import('@/pages/AdminDispatchErrorsHistoryPage'));
export const AdminInboxSyncStatusPage = lazyWithRetry(() => import('@/pages/admin/AdminInboxSyncStatusPage'));
export const AdminEvoApiHealthPage = lazyWithRetry(() => import('@/pages/admin/AdminEvoApiHealthPage'));
export const AchievementsSystemLazy = lazyWithRetry(async () => {
  const m = await import('@/components/gamification/AchievementsSystem');
  return { default: m.AchievementsSystem };
}) as React.LazyExoticComponent<React.ComponentType<{ userId?: string; showCompact?: boolean }>>;
