#!/usr/bin/env bash
# =============================================================================
# introspect-schema.sh
# -----------------------------------------------------------------------------
# Reconstruct supabase/migrations-snapshot/ALL_IN_ONE.sql from the LIVE database
# using ONLY introspection (information_schema + pg_catalog + pg_get_*def).
#
# Why introspection (and not pg_dump)?
#   Lovable Cloud disables pg_dump for end-users. This script produces an
#   idempotent, apply-anywhere SQL snapshot that is functionally equivalent
#   (not byte-identical) to a pg_dump --schema-only for the `public` schema.
#
# Requirements: psql on PATH and PG* env vars set (PGHOST/PGUSER/PGPASSWORD/
# PGDATABASE/PGPORT). On CI, expose these as secrets.
#
# Usage:
#   bash scripts/introspect-schema.sh                 # writes into repo
#   OUT_DIR=/tmp/snap bash scripts/introspect-schema.sh
# =============================================================================
set -euo pipefail

OUT_DIR="${OUT_DIR:-supabase/migrations-snapshot}"
mkdir -p "$OUT_DIR"

STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "▶ Introspecting schema (public) at $STAMP"

# --- 00 extensions -----------------------------------------------------------
cat > "$OUT_DIR/00_extensions.sql" <<'SQL'
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS supabase_vault;
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
SQL

# --- 01 enums ----------------------------------------------------------------
psql -Atq -v ON_ERROR_STOP=1 -o "$TMP/enums.sql" <<'SQL'
SELECT format(
  E'DO $$ BEGIN\n  CREATE TYPE public.%I AS ENUM (%s);\nEXCEPTION WHEN duplicate_object THEN NULL; END $$;',
  t.typname,
  string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder)
)
FROM pg_type t
JOIN pg_enum e ON e.enumtypid = t.oid
JOIN pg_namespace n ON n.oid = t.typnamespace
WHERE n.nspname = 'public'
GROUP BY t.typname
ORDER BY t.typname;
SQL
mv "$TMP/enums.sql" "$OUT_DIR/01_enums.sql"

# --- 02 schema (tables, cols, constraints, indexes, functions, triggers,
#                views, policies, grants) ------------------------------------
SCHEMA_OUT="$OUT_DIR/02_schema_full.sql"
: > "$SCHEMA_OUT"

echo "-- Generated by scripts/introspect-schema.sh at $STAMP" >> "$SCHEMA_OUT"
echo "-- Source: information_schema + pg_catalog introspection (no pg_dump)" >> "$SCHEMA_OUT"
echo "" >> "$SCHEMA_OUT"

# Tables (CREATE TABLE IF NOT EXISTS with columns + defaults + nullability)
psql -Atq -v ON_ERROR_STOP=1 <<'SQL' >> "$SCHEMA_OUT"
WITH cols AS (
  SELECT c.table_name,
         string_agg(
           format('  %I %s%s%s',
             c.column_name,
             CASE WHEN c.data_type='USER-DEFINED' THEN format('public.%I', c.udt_name)
                  WHEN c.data_type='ARRAY' THEN
                    (SELECT format('%s[]', e.data_type) FROM information_schema.element_types e
                      WHERE e.object_schema=c.table_schema AND e.object_name=c.table_name
                        AND e.object_type='TABLE' AND e.collection_type_identifier=c.dtd_identifier
                      LIMIT 1)
                  ELSE c.data_type END,
             CASE WHEN c.is_nullable='NO' THEN ' NOT NULL' ELSE '' END,
             CASE WHEN c.column_default IS NOT NULL THEN ' DEFAULT '||c.column_default ELSE '' END
           ),
           E',\n'
           ORDER BY c.ordinal_position
         ) AS col_defs
  FROM information_schema.columns c
  WHERE c.table_schema='public'
  GROUP BY c.table_name
)
SELECT format(E'CREATE TABLE IF NOT EXISTS public.%I (\n%s\n);\n',
              t.tablename, cols.col_defs)
FROM pg_tables t
JOIN cols ON cols.table_name = t.tablename
WHERE t.schemaname='public'
ORDER BY t.tablename;
SQL

# Primary keys, unique, foreign keys, checks
psql -Atq -v ON_ERROR_STOP=1 <<'SQL' >> "$SCHEMA_OUT"
SELECT format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;',
              c.relname, con.conname, pg_get_constraintdef(con.oid))
FROM pg_constraint con
JOIN pg_class c ON c.oid = con.conrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname='public'
  AND con.contype IN ('p','u','f','c')
ORDER BY c.relname, con.contype, con.conname;
SQL

# Indexes (non-constraint)
psql -Atq -v ON_ERROR_STOP=1 <<'SQL' >> "$SCHEMA_OUT"
SELECT indexdef || ';'
FROM pg_indexes i
WHERE schemaname='public'
  AND NOT EXISTS (
    SELECT 1 FROM pg_constraint c
    WHERE c.conname = i.indexname AND c.connamespace='public'::regnamespace
  )
ORDER BY tablename, indexname;
SQL

# Functions
psql -Atq -v ON_ERROR_STOP=1 <<'SQL' >> "$SCHEMA_OUT"
SELECT pg_get_functiondef(p.oid) || E';\n'
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname='public'
  AND p.prokind IN ('f','p')
ORDER BY p.proname, p.oid;
SQL

# Views
psql -Atq -v ON_ERROR_STOP=1 <<'SQL' >> "$SCHEMA_OUT"
SELECT format(E'CREATE OR REPLACE VIEW public.%I AS\n%s\n',
              viewname, definition)
FROM pg_views WHERE schemaname='public'
ORDER BY viewname;
SQL

# Triggers
psql -Atq -v ON_ERROR_STOP=1 <<'SQL' >> "$SCHEMA_OUT"
SELECT format('DROP TRIGGER IF EXISTS %I ON %s;', t.tgname, c.oid::regclass) || E'\n'
     || pg_get_triggerdef(t.oid) || E';\n'
FROM pg_trigger t
JOIN pg_class c ON c.oid = t.tgrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname='public' AND NOT t.tgisinternal
ORDER BY c.relname, t.tgname;
SQL

# RLS enable + policies
psql -Atq -v ON_ERROR_STOP=1 <<'SQL' >> "$SCHEMA_OUT"
SELECT format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', tablename)
FROM pg_tables WHERE schemaname='public'
  AND rowsecurity = true
ORDER BY tablename;
SQL

psql -Atq -v ON_ERROR_STOP=1 <<'SQL' >> "$SCHEMA_OUT"
SELECT format(
  'DROP POLICY IF EXISTS %I ON public.%I;',
  policyname, tablename
) || E'\n' || format(
  'CREATE POLICY %I ON public.%I AS %s FOR %s TO %s%s%s;',
  policyname, tablename, permissive, cmd,
  array_to_string(roles, ', '),
  CASE WHEN qual IS NOT NULL THEN ' USING ('||qual||')' ELSE '' END,
  CASE WHEN with_check IS NOT NULL THEN ' WITH CHECK ('||with_check||')' ELSE '' END
) || E'\n'
FROM pg_policies
WHERE schemaname='public'
ORDER BY tablename, policyname;
SQL

# Table grants
psql -Atq -v ON_ERROR_STOP=1 <<'SQL' >> "$SCHEMA_OUT"
SELECT format('GRANT %s ON public.%I TO %I;',
              string_agg(DISTINCT privilege_type, ', '),
              table_name, grantee)
FROM information_schema.role_table_grants
WHERE table_schema='public'
  AND grantee IN ('anon','authenticated','service_role')
GROUP BY table_name, grantee
ORDER BY table_name, grantee;
SQL

# --- 03 storage buckets ------------------------------------------------------
psql -Atq -v ON_ERROR_STOP=1 -o "$TMP/buckets.sql" <<'SQL'
SELECT format(
  'INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES (%L, %L, %s, %s, %L) ON CONFLICT (id) DO NOTHING;',
  id, name, public::text,
  COALESCE(file_size_limit::text, 'NULL'),
  allowed_mime_types
)
FROM storage.buckets ORDER BY id;
SQL
mv "$TMP/buckets.sql" "$OUT_DIR/03_storage_buckets.sql"

# --- ALL_IN_ONE --------------------------------------------------------------
{
  echo "-- ============================================================"
  echo "-- ALL_IN_ONE.sql — Public schema snapshot"
  echo "-- Generated by scripts/introspect-schema.sh at $STAMP"
  echo "-- Method: introspection (information_schema + pg_catalog)"
  echo "-- Idempotent; safe to re-run. Wrapped in a single transaction."
  echo "-- ============================================================"
  echo "BEGIN;"
  cat "$OUT_DIR/00_extensions.sql"
  cat "$OUT_DIR/01_enums.sql"
  cat "$OUT_DIR/02_schema_full.sql"
  cat "$OUT_DIR/03_storage_buckets.sql"
  echo "COMMIT;"
} > "$OUT_DIR/ALL_IN_ONE.sql"

echo "✓ Wrote $OUT_DIR/ALL_IN_ONE.sql ($(wc -l < "$OUT_DIR/ALL_IN_ONE.sql") lines, $(du -h "$OUT_DIR/ALL_IN_ONE.sql" | cut -f1))"
