-- ===========================================================
-- Migration: [TÍTULO DESCRITIVO DA MIGRATION]
-- Data: YYYY-MM-DD
-- Autor: [nome/handle]
-- Ticket: [link do ticket ou issue]
--
-- DESCRIÇÃO:
-- [descreva aqui o que essa migration faz e por que]
--
-- ROLLBACK:
-- [descreva como reverter se necessário]
-- ===========================================================

-- Exemplo de migration:
-- CREATE TABLE IF NOT EXISTS zapp.exemplo (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   nome TEXT NOT NULL,
--   criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
--
-- ALTER TABLE zapp.exemplo ENABLE ROW LEVEL SECURITY;
--
-- CREATE POLICY "authenticated users can read"
--   ON zapp.exemplo FOR SELECT TO authenticated USING (TRUE);
--
-- CREATE POLICY "service role full access"
--   ON zapp.exemplo FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

-- LEMBRE-SE:
-- 1. Toda nova tabela DEVE ter RLS habilitado
-- 2. Views DEVEM ter security_invoker = true
-- 3. Funções SECURITY DEFINER DEVEM ter SET search_path
-- 4. NUNCA dar EXECUTE para anon
-- 5. Naming: _backup_*_yyyymmdd para backups
-- 6. VACUUM como statement único no pg_cron
