-- 13 tables referenced by Edge Functions
CREATE TABLE IF NOT EXISTS public.contact_export_log (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, user_id uuid, export_type text, filters jsonb DEFAULT '{}'::jsonb, row_count integer, file_url text, status text DEFAULT 'pending', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.evolution_fallback_events (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, instance_name text, event_type text NOT NULL, payload jsonb DEFAULT '{}'::jsonb, error_message text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.instance_auth_events (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, instance_name text NOT NULL, event_type text NOT NULL, ip_address text, user_agent text, success boolean DEFAULT false, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.instance_processing_pauses (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, instance_name text NOT NULL, paused_by uuid, reason text, paused_at timestamptz DEFAULT now(), resumed_at timestamptz);
CREATE TABLE IF NOT EXISTS public.message_queue (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, instance_name text, remote_jid text, content text, message_type text DEFAULT 'text', media_url text, priority integer DEFAULT 0, status text DEFAULT 'queued', attempts integer DEFAULT 0, scheduled_for timestamptz DEFAULT now(), created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.messages_whatsapp (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, contact_id uuid, instance_name text, remote_jid text, message_id text, content text, message_type text DEFAULT 'text', is_from_me boolean DEFAULT false, status text, media_url text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.nps_invitations (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, contact_id uuid, sent_at timestamptz DEFAULT now(), responded_at timestamptz, score integer, channel text DEFAULT 'whatsapp', status text DEFAULT 'pending', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.proxy_alerts (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, proxy_id text, alert_type text NOT NULL, severity text DEFAULT 'medium', message text, is_resolved boolean DEFAULT false, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.proxy_metrics (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, proxy_id text, requests_total integer DEFAULT 0, requests_blocked integer DEFAULT 0, avg_latency_ms integer, recorded_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.system_logs (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, level text DEFAULT 'info', source text, message text NOT NULL, metadata jsonb DEFAULT '{}'::jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.webauthn_challenges (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, user_id uuid, challenge text NOT NULL, type text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.webhook_audit_log (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, webhook_source text, endpoint text, method text, status_code integer, request_body jsonb, response_body jsonb, duration_ms integer, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.webhook_events_processed (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, event_id text NOT NULL, webhook_source text, event_type text, processed_at timestamptz DEFAULT now(), idempotency_key text UNIQUE);
