-- =============================================================================
-- OBSOLETA - NAO EXECUTAR
-- =============================================================================
-- Esta migration NUNCA pode ser aplicada. Ela aborta no FIX A, a primeira
-- instrucao executavel do arquivo.
--
-- Erros confirmados contra o banco de producao em 2026-07-26:
--
--   FIX A) SELECT ... FROM zapp.feature_flags
--          -> ERRO: relation "zapp.feature_flags" does not exist
--          O comentario do arquivo afirma que a tabela foi criada no "Round 2",
--          mas o Round 2 nunca criou feature_flags (e tambem nunca rodou).
--          Nao ha guarda de existencia, entao o DO block aborta a migration
--          inteira.
--
--   FIX G) CREATE TRIGGER ... EXECUTE FUNCTION zapp.fn_refresh_role_permissions_mv()
--          -> ERRO: function zapp.fn_refresh_role_permissions_mv must return
--             type trigger
--          A funcao retorna void. Faltava um wrapper que retornasse trigger.
--
-- Itens que eram inofensivos porem inuteis:
--
--   FIX D) contact_audit_log.contact_id ja e NOT NULL -> guarda nunca dispara.
--          Alem disso, a estrategia de preencher NULLs com o UUID sentinela
--          00000000-0000-0000-0000-000000000000 corromperia a trilha de
--          auditoria em vez de preserva-la.
--
--   FIX E) idx_zapp_role_permissions_role era duplicata exata de
--          idx_role_permissions_role, que ja existe sobre (role). O repositorio
--          tem varias migrations dedicadas justamente a remover indices
--          duplicados.
--
--   FIX F) zapp.contact_audit_log ja possui o trigger set_updated_at
--          (handle_updated_at). Criar outro seria duplicidade.
--
-- Itens validos, entregues na versao consolidada:
--   FIX B) indice (contact_id, changed_at DESC) em contact_audit_log
--   FIX C) CHECK em contact_audit_log.action
--   FIX G) auto-refresh da MV, com wrapper de trigger correto
--
-- SUBSTITUIDA POR:
--   20260727120000_qa_round_2_3_corrigido_consolidado.sql
--   (aplicada e validada em producao)
-- =============================================================================

SELECT 'MIGRATION OBSOLETA - ver 20260727120000_qa_round_2_3_corrigido_consolidado.sql' AS aviso;
