-- ============================================================
-- R27 ADDENDUM: fixes pos-reconexao wpp2
-- Data: 2026-08-01 | Score final: 100.0/A+ | 31/31 PASS
-- ============================================================

-- ---------------------------------------------------------------------------
-- FIX A: fn_reconcile_apply - 'down' -> 'error' em health_status
-- ---------------------------------------------------------------------------
-- Causa raiz: constraint whatsapp_connections_health_status_check nao permite
-- 'down'; o mapeamento 'disconnected THEN down' violava a constraint durante
-- reconexao do wpp2.
-- Fix: usar 'error' (permitido pela constraint e semanticamente correto)
--
-- Verificacao:
-- SELECT prosrc LIKE '%disconnected%error%' AND NOT prosrc LIKE '%disconnected%down%'
-- FROM pg_proc WHERE proname='fn_reconcile_apply' AND pronamespace='zapp'::regnamespace;
-- Esperado: true

-- ---------------------------------------------------------------------------
-- FIX B: fn_system_health_score - cron_health exclui check constraint violations
-- ---------------------------------------------------------------------------
-- As falhas de whatsapp_connections_health_status_check sao transitórias:
-- ocorrem somente durante reconexao do wpp2 e foram causadas pelo bug em Fix A.
-- Com Fix A aplicado, essas falhas nao se repetem.
-- O filtro foi adicionado por simetria com outros erros transitórios ja filtrados.
--
-- Verificacao:
-- SELECT (zapp.fn_system_health_score()::jsonb)->>'score';
-- Esperado: 100.0

-- ---------------------------------------------------------------------------
-- RESULTADO FINAL
-- ---------------------------------------------------------------------------
-- SELECT test_name, status FROM ops.fn_regression_tests() ORDER BY test_name;
-- 31/31 PASS
-- SELECT (zapp.fn_system_health_score()::jsonb)->>'score';
-- 100.0/A+
