-- ═══════════════════════════════════════════════════════════════════════════════
-- Migration: 20260730000000_baseline_schema.sql
-- Purpose  : Baseline documental do estado atual do schema.
-- Updated  : 2026-08-03 (limpeza de migrations — de 144 para 129 arquivos)
--
-- Contexto:
--   O projeto ZAPP-WEB nasceu no Lovable (Supabase Cloud) e migrou para
--   Supabase self-hosted (VPS AtomicaBR) via dump/restore em 2026-07-16.
--   O dump criou todos os objetos no DB, mas não registrou as migrations.
--
--   As migrations originais do Lovable Cloud (967 arquivos) foram removidas
--   do repositório durante a limpeza de 2026-08-03. Apenas as migrations
--   aplicadas ao self-hosted permanecem (129 arquivos ativos, 88 registradas
--   na tabela supabase_migrations.schema_migrations).
--
--   Esta migration baseline documenta o estado atual do schema para
--   referência futura. NÃO contém DDL executável — os objetos já existem.
--
-- Schemas:
--   zapp (312 tables, 404 views, 700+ RLS policies) — app canônico
--   evo  (193 tables, 16 views, 400+ RLS policies)  — Evolution/WhatsApp
--   public (1 table, 532 views)                       — camada de API
--   financeiro (16 tables), vendas (13), email_app (33), ai (31),
--   bpm (41), ops (20), archive (25), artes (2), logistica (3)
--
-- Migrations ativas (130 arquivos após limpeza 2026-08-03):
--   - 16/07/2026: schema hardening v1-v6, fix public→zapp, RLS hardening
--   - 17/07/2026: fix DLQ RPCs, missing functions, schema hardening v4-v6
--   - 20/07/2026: fix settings realtime publication
--   - 24/07/2026: evo schema housekeeping, realtime publications,
--                 evolution_sentiment_analysis, secdef hardening
--   - 27/07/2026: QA round 2-3, contacts idx, pipeline health RPCs,
--                 backfill contact_id, secdef hardening, webhook idx
--   - 28/07/2026: DDL event trigger, autofix schemas, rate limit guards,
--                 explicit policies, pgbouncer hardening
--   - 29/07/2026: drop FKs evo→zapp, secdef hardening,
--                 reactivate cron analytics-log-retention
--   - 30/07/2026: baseline documental, batch RPCs v2 canonical,
--                 perf notifications partial index, R25 fixes
--   - 31/07/2026: realtime assertion, RLS impact preview,
--                 excessive privileges revoke, anon hardening
--   - 01/08/2026: P0 privilege escalation, RLS security tables,
--                 warroom alerts, unique constraints, merge duplicates,
--                 RLS lotes 1-5, feature flags, storage buckets,
--                 R25 P0/P1 fixes, R26/R27/R28 security,
--                 INFRA-01 v2 triggers, RLS consolidated sync
--   - 02/08/2026: financeiro auth guards, audio bucket fix,
--                 security fixes, realtime all gaps,
--                 search_contacts_cursor v2, edge function view proxies,
--                 etapas 3-17 (JWT, multi-tenant, SECDEF, contacts,
--                 crons, merge, webhook cleanup, connections, notes)
--   - 03/08/2026: deprecate Lovable parity functions, factor X fixes,
--                 evolution retry columns, intelligence multi-instance,
--                 avatar backup, media cache RLS, auth guards,
--                 proxy ecosystem drop, rate limit revoke,
--                 performance indexes, batch RPCs (contacts 360, inbox)
--
-- Limpeza 2026-08-03 — Removidos:
--   - 4 arquivos .md obsoletos (RLS_MIGRATION_FILES_README.md, etc.)
--   - lgpd_deploy.sql (deploy de Edge Function, não migration)
--   - storage_migration_plan.sql (documento de planejamento, 0 SQL executável)
--   - p23_p26_omissions_decision.sql (COMMENTs apenas, sem DDL)
--   - rpc_get_pipeline_health.sql (superseded por v2)
--   - batch_rpcs_bootstrap_dashboard.sql (superseded por v2 canonical)
--   - infra01_consolidate_messages_view_triggers.sql (superseded por v2)
--   - 4 migrations documental-only (SQL incorporado em r28e_executable)
-- ═══════════════════════════════════════════════════════════════════════════════

-- Esta migration é puramente documental. Todos os objetos já existem
-- no DB self-hosted. Nenhum DDL é executado.

DO $$
BEGIN
  RAISE NOTICE 'Baseline 2026-08-03: schema documentado em 130 migrations ativas (88 registradas em supabase_migrations).';
END $$;
