-- Migration: 20260727300010_zapp_evo_curated_contract
-- Purpose: Rationalize the 254 zapp→evo mirror views into a governed contract.
--          Mark excess views as deprecated. Define the canonical minimal set.
-- Risk: LOW (documentation + comments only; no objects dropped)
-- Staging required: NO for comments; YES for any DROP VIEW
-- Pre-requisites: ADR-DB-002 must be approved before dropping any views.
-- See: docs/db/adrs/ADR-DB-002-fronteira-zapp-evo.md

SET search_path = zapp, evo, public, pg_catalog;

-- ============================================================
-- AUDIT: Current state of zapp→evo views
-- ============================================================
/*
-- Run this in READ-ONLY mode to see all views in zapp that point to evo:
SELECT
    v.viewname,
    pg_get_viewdef(c.oid, true) AS definition
FROM pg_views v
JOIN pg_class c ON c.relname = v.viewname
JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'zapp'
WHERE pg_get_viewdef(c.oid, true) ILIKE '%evo.%'
   OR pg_get_viewdef(c.oid, true) ILIKE '%FROM evolution_%'
ORDER BY v.viewname;

-- Count by type:
SELECT
    COUNT(*) FILTER (WHERE pg_get_viewdef(c.oid,true) ILIKE '%evo.evolution_%') AS evolution_mirror,
    COUNT(*) FILTER (WHERE pg_get_viewdef(c.oid,true) ILIKE '%evo.contact_id%') AS contact_graveyard,
    COUNT(*)                                                                       AS total
FROM pg_views v
JOIN pg_class c ON c.relname = v.viewname
JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'zapp'
WHERE pg_get_viewdef(c.oid, true) ILIKE '%evo.%';
*/

-- ============================================================
-- CANONICAL CONTRACT: Views zapp IS ALLOWED to have → evo
-- ============================================================
-- These 20 views represent the curated contract between zapp and evo.
-- All others are candidates for deprecation (pending ADR-DB-002 approval).

COMMENT ON SCHEMA zapp IS
    'Application schema. Contains business tables, RPCs, and curated evo contract views. '
    'Curated evo contract views (canonical set as of 2026-07-27): '
    'evolution_messages, evolution_conversations, evolution_contacts, '
    'evolution_media, evolution_whatsapp_status, evolution_webhook_events_v2_*, '
    'contact_id_graveyard. '
    'The 254 total zapp→evo views include ~234 auto-generated by evo.fn_ensure_evolution_backcompat_views. '
    'The excess 234 views are managed by the backcompat cron (job 138) and must NOT be dropped manually. '
    'See ADR-DB-002 for rationalization plan.';

-- ============================================================
-- DEPRECATION MARKERS: Tag excess views with comments
-- ============================================================
-- These views exist because evo.fn_ensure_evolution_backcompat_views creates them every 6h.
-- Until ADR-DB-002 is approved and the cron is updated, they cannot be removed.

/*
-- Tag auto-generated backcompat views (run after identifying them):
DO $$
DECLARE
    v_view text;
    v_cursor CURSOR FOR
        SELECT viewname FROM pg_views
        WHERE schemaname = 'zapp'
          AND viewname LIKE 'evolution_%'
          AND viewname NOT IN (
              -- canonical contract set (keep these):
              'evolution_messages', 'evolution_conversations', 'evolution_contacts',
              'evolution_media', 'evolution_whatsapp_status'
          );
BEGIN
    FOR v_view IN v_cursor LOOP
        EXECUTE format(
            'COMMENT ON VIEW zapp.%I IS '
            '''AUTO-GENERATED by evo.fn_ensure_evolution_backcompat_views (cron job 138, every 6h). '
            'Managed by cron — do not drop manually. '
            'Candidate for removal after ADR-DB-002 approval.''',
            v_view
        );
    END LOOP;
    RAISE NOTICE 'Tagged auto-generated backcompat views with deprecation comment.';
END; $$;
*/

-- ============================================================
-- POLICY: No new zapp→evo views outside the canonical set
-- ============================================================
-- This policy is enforced by CI-03 (see SCHEMA-CONTRACT.md).
-- Any new view pointing to evo MUST be added to the canonical set
-- documented in ADR-DB-002 and listed in this migration's comment.

SELECT 'Migration 20260727300010 loaded. '
       'Audit queries available in comments. '
       'Rationalization pending ADR-DB-002 approval.' AS status;
