// Generated by supabase_generate_typescript_types
// DO NOT EDIT MANUALLY — regenerate with supabase_generate_typescript_types
// Generated: 2026-07-30T14:43:39.126Z

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      _wal_slot_guard_events: {
        Row: {
          id: number
          detected_at: string
          slot_name: string
          lag_mb: number | null
          frozen_sec: number | null
          action_taken: string
          details: Json
        }
        Insert: {
          id?: number
          detected_at?: string
          slot_name: string
          lag_mb?: number | null
          frozen_sec?: number | null
          action_taken: string
          details?: Json
        }
        Update: {
          id?: number
          detected_at?: string
          slot_name?: string
          lag_mb?: number | null
          frozen_sec?: number | null
          action_taken?: string
          details?: Json
        }
      }
      agent_achievements: {
        Row: {
          achievement_description: string | null
          achievement_name: string | null
          achievement_type: string | null
          earned_at: string | null
          id: string | null
          profile_id: string | null
          xp_earned: number | null
        }
        Insert: {
          achievement_description?: string | null
          achievement_name?: string | null
          achievement_type?: string | null
          earned_at?: string | null
          id?: string | null
          profile_id?: string | null
          xp_earned?: number | null
        }
        Update: {
          achievement_description?: string | null
          achievement_name?: string | null
          achievement_type?: string | null
          earned_at?: string | null
          id?: string | null
          profile_id?: string | null
          xp_earned?: number | null
        }
      }
      agent_installed_skills: {
        Row: {
          id: string | null
          agent_id: string | null
          skill_id: string | null
          installed_at: string | null
          config_overrides: Json | null
        }
        Insert: {
          id?: string | null
          agent_id?: string | null
          skill_id?: string | null
          installed_at?: string | null
          config_overrides?: Json | null
        }
        Update: {
          id?: string | null
          agent_id?: string | null
          skill_id?: string | null
          installed_at?: string | null
          config_overrides?: Json | null
        }
      }
      agent_memories: {
        Row: {
          id: string | null
          workspace_id: string | null
          memory_type: string | null
          content: string | null
          source: string | null
          relevance_score: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string | null
          workspace_id?: string | null
          memory_type?: string | null
          content?: string | null
          source?: string | null
          relevance_score?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string | null
          workspace_id?: string | null
          memory_type?: string | null
          content?: string | null
          source?: string | null
          relevance_score?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      agent_permissions: {
        Row: {
          id: string | null
          agent_id: string | null
          user_id: string | null
          permission_level: string | null
          granted_by: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          agent_id?: string | null
          user_id?: string | null
          permission_level?: string | null
          granted_by?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          agent_id?: string | null
          user_id?: string | null
          permission_level?: string | null
          granted_by?: string | null
          created_at?: string | null
        }
      }
      agent_presence: {
        Row: {
          id: string | null
          user_id: string | null
          status: string | null
          status_message: string | null
          current_queue_id: string | null
          active_conversations: number | null
          max_conversations: number | null
          last_activity_at: string | null
          went_online_at: string | null
          went_offline_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string | null
          user_id?: string | null
          status?: string | null
          status_message?: string | null
          current_queue_id?: string | null
          active_conversations?: number | null
          max_conversations?: number | null
          last_activity_at?: string | null
          went_online_at?: string | null
          went_offline_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string | null
          user_id?: string | null
          status?: string | null
          status_message?: string | null
          current_queue_id?: string | null
          active_conversations?: number | null
          max_conversations?: number | null
          last_activity_at?: string | null
          went_online_at?: string | null
          went_offline_at?: string | null
          updated_at?: string | null
        }
      }
      agent_skills: {
        Row: {
          id: string | null
          agent_id: string | null
          skill_name: string | null
          description: string | null
          pattern: string | null
          success_count: number | null
          failure_count: number | null
          confidence: number | null
          source_trace_id: string | null
          created_at: string | null
          updated_at: string | null
          profile_id: string | null
          skill_level: number | null
        }
        Insert: {
          id?: string | null
          agent_id?: string | null
          skill_name?: string | null
          description?: string | null
          pattern?: string | null
          success_count?: number | null
          failure_count?: number | null
          confidence?: number | null
          source_trace_id?: string | null
          created_at?: string | null
          updated_at?: string | null
          profile_id?: string | null
          skill_level?: number | null
        }
        Update: {
          id?: string | null
          agent_id?: string | null
          skill_name?: string | null
          description?: string | null
          pattern?: string | null
          success_count?: number | null
          failure_count?: number | null
          confidence?: number | null
          source_trace_id?: string | null
          created_at?: string | null
          updated_at?: string | null
          profile_id?: string | null
          skill_level?: number | null
        }
      }
      agent_stats: {
        Row: {
          achievements_count: number | null
          avg_response_time_seconds: number | null
          best_streak: number | null
          conversations_resolved: number | null
          created_at: string | null
          current_streak: number | null
          customer_satisfaction_score: number | null
          id: string | null
          level: number | null
          messages_received: number | null
          messages_sent: number | null
          profile_id: string | null
          updated_at: string | null
          xp: number | null
        }
        Insert: {
          achievements_count?: number | null
          avg_response_time_seconds?: number | null
          best_streak?: number | null
          conversations_resolved?: number | null
          created_at?: string | null
          current_streak?: number | null
          customer_satisfaction_score?: number | null
          id?: string | null
          level?: number | null
          messages_received?: number | null
          messages_sent?: number | null
          profile_id?: string | null
          updated_at?: string | null
          xp?: number | null
        }
        Update: {
          achievements_count?: number | null
          avg_response_time_seconds?: number | null
          best_streak?: number | null
          conversations_resolved?: number | null
          created_at?: string | null
          current_streak?: number | null
          customer_satisfaction_score?: number | null
          id?: string | null
          level?: number | null
          messages_received?: number | null
          messages_sent?: number | null
          profile_id?: string | null
          updated_at?: string | null
          xp?: number | null
        }
      }
      agent_templates: {
        Row: {
          id: string | null
          name: string | null
          description: string | null
          category: string | null
          icon: string | null
          config: Json | null
          is_public: boolean | null
          usage_count: number | null
          created_by: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          name?: string | null
          description?: string | null
          category?: string | null
          icon?: string | null
          config?: Json | null
          is_public?: boolean | null
          usage_count?: number | null
          created_by?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          name?: string | null
          description?: string | null
          category?: string | null
          icon?: string | null
          config?: Json | null
          is_public?: boolean | null
          usage_count?: number | null
          created_by?: string | null
          created_at?: string | null
        }
      }
      agent_traces: {
        Row: {
          id: string | null
          agent_id: string | null
          user_id: string | null
          session_id: string | null
          level: unknown | null
          event: string | null
          input: Json | null
          output: Json | null
          metadata: Json | null
          latency_ms: number | null
          tokens_used: number | null
          cost_usd: number | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          agent_id?: string | null
          user_id?: string | null
          session_id?: string | null
          level?: unknown | null
          event?: string | null
          input?: Json | null
          output?: Json | null
          metadata?: Json | null
          latency_ms?: number | null
          tokens_used?: number | null
          cost_usd?: number | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          agent_id?: string | null
          user_id?: string | null
          session_id?: string | null
          level?: unknown | null
          event?: string | null
          input?: Json | null
          output?: Json | null
          metadata?: Json | null
          latency_ms?: number | null
          tokens_used?: number | null
          cost_usd?: number | null
          created_at?: string | null
        }
      }
      agent_usage: {
        Row: {
          id: string | null
          agent_id: string | null
          user_id: string | null
          date: string | null
          requests: number | null
          tokens_input: number | null
          tokens_output: number | null
          total_cost_usd: number | null
          avg_latency_ms: number | null
          error_count: number | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          agent_id?: string | null
          user_id?: string | null
          date?: string | null
          requests?: number | null
          tokens_input?: number | null
          tokens_output?: number | null
          total_cost_usd?: number | null
          avg_latency_ms?: number | null
          error_count?: number | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          agent_id?: string | null
          user_id?: string | null
          date?: string | null
          requests?: number | null
          tokens_input?: number | null
          tokens_output?: number | null
          total_cost_usd?: number | null
          avg_latency_ms?: number | null
          error_count?: number | null
          created_at?: string | null
        }
      }
      agent_versions: {
        Row: {
          id: string | null
          agent_id: string | null
          version: number | null
          config: Json | null
          name: string | null
          model: string | null
          persona: string | null
          mission: string | null
          change_summary: string | null
          created_by: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          agent_id?: string | null
          version?: number | null
          config?: Json | null
          name?: string | null
          model?: string | null
          persona?: string | null
          mission?: string | null
          change_summary?: string | null
          created_by?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          agent_id?: string | null
          version?: number | null
          config?: Json | null
          name?: string | null
          model?: string | null
          persona?: string | null
          mission?: string | null
          change_summary?: string | null
          created_by?: string | null
          created_at?: string | null
        }
      }
      agent_visibility_grants: {
        Row: {
          agent_id: string | null
          can_see_agent_id: string | null
          created_at: string | null
          granted_by: string | null
          id: string | null
        }
        Insert: {
          agent_id?: string | null
          can_see_agent_id?: string | null
          created_at?: string | null
          granted_by?: string | null
          id?: string | null
        }
        Update: {
          agent_id?: string | null
          can_see_agent_id?: string | null
          created_at?: string | null
          granted_by?: string | null
          id?: string | null
        }
      }
      agents: {
        Row: {
          id: string | null
          user_id: string | null
          name: string | null
          mission: string | null
          persona: string | null
          avatar_emoji: string | null
          model: string | null
          reasoning: string | null
          status: unknown | null
          version: number | null
          config: Json | null
          tags: string[] | null
          is_template: boolean | null
          template_category: string | null
          created_at: string | null
          updated_at: string | null
          workspace_id: string | null
        }
        Insert: {
          id?: string | null
          user_id?: string | null
          name?: string | null
          mission?: string | null
          persona?: string | null
          avatar_emoji?: string | null
          model?: string | null
          reasoning?: string | null
          status?: unknown | null
          version?: number | null
          config?: Json | null
          tags?: string[] | null
          is_template?: boolean | null
          template_category?: string | null
          created_at?: string | null
          updated_at?: string | null
          workspace_id?: string | null
        }
        Update: {
          id?: string | null
          user_id?: string | null
          name?: string | null
          mission?: string | null
          persona?: string | null
          avatar_emoji?: string | null
          model?: string | null
          reasoning?: string | null
          status?: unknown | null
          version?: number | null
          config?: Json | null
          tags?: string[] | null
          is_template?: boolean | null
          template_category?: string | null
          created_at?: string | null
          updated_at?: string | null
          workspace_id?: string | null
        }
      }
      ai_conversation_tags: {
        Row: {
          confidence: number | null
          contact_id: string | null
          created_at: string | null
          id: string | null
          source: string | null
          tag_name: string | null
        }
        Insert: {
          confidence?: number | null
          contact_id?: string | null
          created_at?: string | null
          id?: string | null
          source?: string | null
          tag_name?: string | null
        }
        Update: {
          confidence?: number | null
          contact_id?: string | null
          created_at?: string | null
          id?: string | null
          source?: string | null
          tag_name?: string | null
        }
      }
      alert_channels: {
        Row: {
          id: number | null
          name: string | null
          channel_type: string | null
          config: Json | null
          min_severity: string | null
          is_active: boolean | null
          created_at: string | null
        }
        Insert: {
          id?: number | null
          name?: string | null
          channel_type?: string | null
          config?: Json | null
          min_severity?: string | null
          is_active?: boolean | null
          created_at?: string | null
        }
        Update: {
          id?: number | null
          name?: string | null
          channel_type?: string | null
          config?: Json | null
          min_severity?: string | null
          is_active?: boolean | null
          created_at?: string | null
        }
      }
      alert_dispatch_state: {
        Row: {
          alert_key: string | null
          last_sent_at: string | null
          last_severity: string | null
          count_1h: number | null
        }
        Insert: {
          alert_key?: string | null
          last_sent_at?: string | null
          last_severity?: string | null
          count_1h?: number | null
        }
        Update: {
          alert_key?: string | null
          last_sent_at?: string | null
          last_severity?: string | null
          count_1h?: number | null
        }
      }
      alerts: {
        Row: {
          id: string | null
          workspace_id: string | null
          agent_id: string | null
          severity: string | null
          title: string | null
          message: string | null
          is_resolved: boolean | null
          resolved_at: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          workspace_id?: string | null
          agent_id?: string | null
          severity?: string | null
          title?: string | null
          message?: string | null
          is_resolved?: boolean | null
          resolved_at?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          workspace_id?: string | null
          agent_id?: string | null
          severity?: string | null
          title?: string | null
          message?: string | null
          is_resolved?: boolean | null
          resolved_at?: string | null
          created_at?: string | null
        }
      }
      allowed_countries: {
        Row: {
          added_by: string | null
          country_code: string | null
          country_name: string | null
          created_at: string | null
          id: string | null
        }
        Insert: {
          added_by?: string | null
          country_code?: string | null
          country_name?: string | null
          created_at?: string | null
          id?: string | null
        }
        Update: {
          added_by?: string | null
          country_code?: string | null
          country_name?: string | null
          created_at?: string | null
          id?: string | null
        }
      }
      api_keys: {
        Row: {
          id: string | null
          user_id: string | null
          workspace_id: string | null
          name: string | null
          key_prefix: string | null
          key_hash: string | null
          scopes: string[] | null
          is_active: boolean | null
          last_used_at: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string | null
          user_id?: string | null
          workspace_id?: string | null
          name?: string | null
          key_prefix?: string | null
          key_hash?: string | null
          scopes?: string[] | null
          is_active?: boolean | null
          last_used_at?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string | null
          user_id?: string | null
          workspace_id?: string | null
          name?: string | null
          key_prefix?: string | null
          key_hash?: string | null
          scopes?: string[] | null
          is_active?: boolean | null
          last_used_at?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      app_error_logs: {
        Row: {
          id: string | null
          error_id: string | null
          module: string | null
          message: string | null
          stack: string | null
          component_stack: string | null
          user_agent: string | null
          url: string | null
          timestamp: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          error_id?: string | null
          module?: string | null
          message?: string | null
          stack?: string | null
          component_stack?: string | null
          user_agent?: string | null
          url?: string | null
          timestamp?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          error_id?: string | null
          module?: string | null
          message?: string | null
          stack?: string | null
          component_stack?: string | null
          user_agent?: string | null
          url?: string | null
          timestamp?: string | null
          created_at?: string | null
        }
      }
      app_notifications: {
        Row: {
          id: string | null
          user_id: string | null
          title: string | null
          body: string | null
          type: string | null
          entity_type: string | null
          entity_id: string | null
          is_read: boolean | null
          action_url: string | null
          metadata: Json | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          user_id?: string | null
          title?: string | null
          body?: string | null
          type?: string | null
          entity_type?: string | null
          entity_id?: string | null
          is_read?: boolean | null
          action_url?: string | null
          metadata?: Json | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          user_id?: string | null
          title?: string | null
          body?: string | null
          type?: string | null
          entity_type?: string | null
          entity_id?: string | null
          is_read?: boolean | null
          action_url?: string | null
          metadata?: Json | null
          created_at?: string | null
        }
      }
      app_settings: {
        Row: {
          id: string | null
          created_at: string | null
          updated_at: string | null
          description: string | null
          key: string | null
          value: Json | null
        }
        Insert: {
          id?: string | null
          created_at?: string | null
          updated_at?: string | null
          description?: string | null
          key?: string | null
          value?: Json | null
        }
        Update: {
          id?: string | null
          created_at?: string | null
          updated_at?: string | null
          description?: string | null
          key?: string | null
          value?: Json | null
        }
      }
      audio_meme_categories: {
        Row: {
          id: string | null
          slug: string | null
          label_pt: string | null
          label_en: string | null
          emoji: string | null
          sort_order: number | null
          is_active: boolean | null
          meme_count: number | null
          total_uses: number | null
        }
        Insert: {
          id?: string | null
          slug?: string | null
          label_pt?: string | null
          label_en?: string | null
          emoji?: string | null
          sort_order?: number | null
          is_active?: boolean | null
          meme_count?: number | null
          total_uses?: number | null
        }
        Update: {
          id?: string | null
          slug?: string | null
          label_pt?: string | null
          label_en?: string | null
          emoji?: string | null
          sort_order?: number | null
          is_active?: boolean | null
          meme_count?: number | null
          total_uses?: number | null
        }
      }
      audio_meme_favorites: {
        Row: {
          id: string | null
          user_id: string | null
          meme_id: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          user_id?: string | null
          meme_id?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          user_id?: string | null
          meme_id?: string | null
          created_at?: string | null
        }
      }
      audio_memes: {
        Row: {
          audio_url: string | null
          category: string | null
          created_at: string | null
          duration_seconds: number | null
          id: string | null
          is_favorite: boolean | null
          name: string | null
          uploaded_by: string | null
          use_count: number | null
          updated_at: string | null
          is_active: boolean | null
          tags: string[] | null
          file_hash: string | null
          file_size: number | null
          mime_type: string | null
          owner_id: string | null
        }
        Insert: {
          audio_url?: string | null
          category?: string | null
          created_at?: string | null
          duration_seconds?: number | null
          id?: string | null
          is_favorite?: boolean | null
          name?: string | null
          uploaded_by?: string | null
          use_count?: number | null
          updated_at?: string | null
          is_active?: boolean | null
          tags?: string[] | null
          file_hash?: string | null
          file_size?: number | null
          mime_type?: string | null
          owner_id?: string | null
        }
        Update: {
          audio_url?: string | null
          category?: string | null
          created_at?: string | null
          duration_seconds?: number | null
          id?: string | null
          is_favorite?: boolean | null
          name?: string | null
          uploaded_by?: string | null
          use_count?: number | null
          updated_at?: string | null
          is_active?: boolean | null
          tags?: string[] | null
          file_hash?: string | null
          file_size?: number | null
          mime_type?: string | null
          owner_id?: string | null
        }
      }
      audit_log_tables: {
        Row: {
          id: number | null
          tbl_name: string | null
          operation: string | null
          row_id: string | null
          changed_by: string | null
          changed_fields: Json | null
          old_values: Json | null
          new_values: Json | null
          created_at: string | null
        }
        Insert: {
          id?: number | null
          tbl_name?: string | null
          operation?: string | null
          row_id?: string | null
          changed_by?: string | null
          changed_fields?: Json | null
          old_values?: Json | null
          new_values?: Json | null
          created_at?: string | null
        }
        Update: {
          id?: number | null
          tbl_name?: string | null
          operation?: string | null
          row_id?: string | null
          changed_by?: string | null
          changed_fields?: Json | null
          old_values?: Json | null
          new_values?: Json | null
          created_at?: string | null
        }
      }
      audit_logs: {
        Row: {
          action: string | null
          created_at: string | null
          details: Json | null
          entity_id: string | null
          entity_type: string | null
          id: string | null
          ip_address: string | null
          user_agent: string | null
          user_id: string | null
          event_type: string | null
          resource: string | null
          status: string | null
        }
        Insert: {
          action?: string | null
          created_at?: string | null
          details?: Json | null
          entity_id?: string | null
          entity_type?: string | null
          id?: string | null
          ip_address?: string | null
          user_agent?: string | null
          user_id?: string | null
          event_type?: string | null
          resource?: string | null
          status?: string | null
        }
        Update: {
          action?: string | null
          created_at?: string | null
          details?: Json | null
          entity_id?: string | null
          entity_type?: string | null
          id?: string | null
          ip_address?: string | null
          user_agent?: string | null
          user_id?: string | null
          event_type?: string | null
          resource?: string | null
          status?: string | null
        }
      }
      audit_results: {
        Row: {
          id: number | null
          audit_name: string | null
          result: Json | null
          created_at: string | null
        }
        Insert: {
          id?: number | null
          audit_name?: string | null
          result?: Json | null
          created_at?: string | null
        }
        Update: {
          id?: number | null
          audit_name?: string | null
          result?: Json | null
          created_at?: string | null
        }
      }
      auto_close_config: {
        Row: {
          close_message: string | null
          created_at: string | null
          id: string | null
          inactivity_hours: number | null
          is_enabled: boolean | null
          updated_at: string | null
          updated_by: string | null
        }
        Insert: {
          close_message?: string | null
          created_at?: string | null
          id?: string | null
          inactivity_hours?: number | null
          is_enabled?: boolean | null
          updated_at?: string | null
          updated_by?: string | null
        }
        Update: {
          close_message?: string | null
          created_at?: string | null
          id?: string | null
          inactivity_hours?: number | null
          is_enabled?: boolean | null
          updated_at?: string | null
          updated_by?: string | null
        }
      }
      automation_executions: {
        Row: {
          id: string | null
          automation_id: string | null
          rule_id: string | null
          contact_id: string | null
          trigger_event: string | null
          status: string | null
          result: Json | null
          error_message: string | null
          executed_at: string | null
          created_at: string | null
          acted_at: string | null
          acted_by: string | null
          applied_tags: string[] | null
          assigned_to: string | null
          channel_id: string | null
          department_id: string | null
          error_at: string | null
          instance_name: string | null
          kb_sources: string[] | null
          reassigned_to: string | null
          recommended_tag: string | null
          remote_jid: string | null
          rule_snapshot: Json | null
          suggestion_text: string | null
          trigger_payload: Json | null
        }
        Insert: {
          id?: string | null
          automation_id?: string | null
          rule_id?: string | null
          contact_id?: string | null
          trigger_event?: string | null
          status?: string | null
          result?: Json | null
          error_message?: string | null
          executed_at?: string | null
          created_at?: string | null
          acted_at?: string | null
          acted_by?: string | null
          applied_tags?: string[] | null
          assigned_to?: string | null
          channel_id?: string | null
          department_id?: string | null
          error_at?: string | null
          instance_name?: string | null
          kb_sources?: string[] | null
          reassigned_to?: string | null
          recommended_tag?: string | null
          remote_jid?: string | null
          rule_snapshot?: Json | null
          suggestion_text?: string | null
          trigger_payload?: Json | null
        }
        Update: {
          id?: string | null
          automation_id?: string | null
          rule_id?: string | null
          contact_id?: string | null
          trigger_event?: string | null
          status?: string | null
          result?: Json | null
          error_message?: string | null
          executed_at?: string | null
          created_at?: string | null
          acted_at?: string | null
          acted_by?: string | null
          applied_tags?: string[] | null
          assigned_to?: string | null
          channel_id?: string | null
          department_id?: string | null
          error_at?: string | null
          instance_name?: string | null
          kb_sources?: string[] | null
          reassigned_to?: string | null
          recommended_tag?: string | null
          remote_jid?: string | null
          rule_snapshot?: Json | null
          suggestion_text?: string | null
          trigger_payload?: Json | null
        }
      }
      automation_rules: {
        Row: {
          id: string | null
          name: string | null
          description: string | null
          trigger_type: string | null
          trigger_config: Json | null
          conditions: Json | null
          actions: Json | null
          is_active: boolean | null
          priority: number | null
          execution_count: number | null
          last_executed_at: string | null
          created_by: string | null
          created_at: string | null
          updated_at: string | null
          channel_id: string | null
          cooldown_seconds: number | null
          department_id: string | null
        }
        Insert: {
          id?: string | null
          name?: string | null
          description?: string | null
          trigger_type?: string | null
          trigger_config?: Json | null
          conditions?: Json | null
          actions?: Json | null
          is_active?: boolean | null
          priority?: number | null
          execution_count?: number | null
          last_executed_at?: string | null
          created_by?: string | null
          created_at?: string | null
          updated_at?: string | null
          channel_id?: string | null
          cooldown_seconds?: number | null
          department_id?: string | null
        }
        Update: {
          id?: string | null
          name?: string | null
          description?: string | null
          trigger_type?: string | null
          trigger_config?: Json | null
          conditions?: Json | null
          actions?: Json | null
          is_active?: boolean | null
          priority?: number | null
          execution_count?: number | null
          last_executed_at?: string | null
          created_by?: string | null
          created_at?: string | null
          updated_at?: string | null
          channel_id?: string | null
          cooldown_seconds?: number | null
          department_id?: string | null
        }
      }
      automations: {
        Row: {
          actions: Json | null
          created_at: string | null
          created_by: string | null
          description: string | null
          id: string | null
          is_active: boolean | null
          last_triggered_at: string | null
          name: string | null
          trigger_config: Json | null
          trigger_count: number | null
          trigger_type: string | null
          updated_at: string | null
          priority: number | null
          cooldown_seconds: number | null
          channel_id: string | null
          department_id: string | null
        }
        Insert: {
          actions?: Json | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          id?: string | null
          is_active?: boolean | null
          last_triggered_at?: string | null
          name?: string | null
          trigger_config?: Json | null
          trigger_count?: number | null
          trigger_type?: string | null
          updated_at?: string | null
          priority?: number | null
          cooldown_seconds?: number | null
          channel_id?: string | null
          department_id?: string | null
        }
        Update: {
          actions?: Json | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          id?: string | null
          is_active?: boolean | null
          last_triggered_at?: string | null
          name?: string | null
          trigger_config?: Json | null
          trigger_count?: number | null
          trigger_type?: string | null
          updated_at?: string | null
          priority?: number | null
          cooldown_seconds?: number | null
          channel_id?: string | null
          department_id?: string | null
        }
      }
      avatars: {
        Row: {
          id: string | null
          created_at: string | null
          updated_at: string | null
          is_default: boolean | null
          name: string | null
          url: string | null
          user_id: string | null
        }
        Insert: {
          id?: string | null
          created_at?: string | null
          updated_at?: string | null
          is_default?: boolean | null
          name?: string | null
          url?: string | null
          user_id?: string | null
        }
        Update: {
          id?: string | null
          created_at?: string | null
          updated_at?: string | null
          is_default?: boolean | null
          name?: string | null
          url?: string | null
          user_id?: string | null
        }
      }
      away_messages: {
        Row: {
          content: string | null
          created_at: string | null
          id: string | null
          is_enabled: boolean | null
          updated_at: string | null
          whatsapp_connection_id: string | null
        }
        Insert: {
          content?: string | null
          created_at?: string | null
          id?: string | null
          is_enabled?: boolean | null
          updated_at?: string | null
          whatsapp_connection_id?: string | null
        }
        Update: {
          content?: string | null
          created_at?: string | null
          id?: string | null
          is_enabled?: boolean | null
          updated_at?: string | null
          whatsapp_connection_id?: string | null
        }
      }
      batch_jobs: {
        Row: {
          id: string | null
          workspace_id: string | null
          type: string | null
          status: string | null
          total_items: number | null
          processed_items: number | null
          failed_items: number | null
          config: Json | null
          error: string | null
          started_at: string | null
          completed_at: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          workspace_id?: string | null
          type?: string | null
          status?: string | null
          total_items?: number | null
          processed_items?: number | null
          failed_items?: number | null
          config?: Json | null
          error?: string | null
          started_at?: string | null
          completed_at?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          workspace_id?: string | null
          type?: string | null
          status?: string | null
          total_items?: number | null
          processed_items?: number | null
          failed_items?: number | null
          config?: Json | null
          error?: string | null
          started_at?: string | null
          completed_at?: string | null
          created_at?: string | null
        }
      }
      blocked_countries: {
        Row: {
          blocked_by: string | null
          country_code: string | null
          country_name: string | null
          created_at: string | null
          id: string | null
          reason: string | null
        }
        Insert: {
          blocked_by?: string | null
          country_code?: string | null
          country_name?: string | null
          created_at?: string | null
          id?: string | null
          reason?: string | null
        }
        Update: {
          blocked_by?: string | null
          country_code?: string | null
          country_name?: string | null
          created_at?: string | null
          id?: string | null
          reason?: string | null
        }
      }
      blocked_ips: {
        Row: {
          blocked_at: string | null
          blocked_by: string | null
          created_at: string | null
          expires_at: string | null
          id: string | null
          ip_address: string | null
          is_permanent: boolean | null
          last_attempt_at: string | null
          reason: string | null
          request_count: number | null
        }
        Insert: {
          blocked_at?: string | null
          blocked_by?: string | null
          created_at?: string | null
          expires_at?: string | null
          id?: string | null
          ip_address?: string | null
          is_permanent?: boolean | null
          last_attempt_at?: string | null
          reason?: string | null
          request_count?: number | null
        }
        Update: {
          blocked_at?: string | null
          blocked_by?: string | null
          created_at?: string | null
          expires_at?: string | null
          id?: string | null
          ip_address?: string | null
          is_permanent?: boolean | null
          last_attempt_at?: string | null
          reason?: string | null
          request_count?: number | null
        }
      }
      bpm_activity_log: {
        Row: {
          id: string | null
          workspace_id: string | null
          flow_id: string | null
          card_id: string | null
          register_id: string | null
          user_id: string | null
          action: string | null
          entity_type: string | null
          entity_id: string | null
          changes: Json | null
          metadata: Json | null
          ip_address: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          workspace_id?: string | null
          flow_id?: string | null
          card_id?: string | null
          register_id?: string | null
          user_id?: string | null
          action?: string | null
          entity_type?: string | null
          entity_id?: string | null
          changes?: Json | null
          metadata?: Json | null
          ip_address?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          workspace_id?: string | null
          flow_id?: string | null
          card_id?: string | null
          register_id?: string | null
          user_id?: string | null
          action?: string | null
          entity_type?: string | null
          entity_id?: string | null
          changes?: Json | null
          metadata?: Json | null
          ip_address?: string | null
          created_at?: string | null
        }
      }
      bpm_automation_actions: {
        Row: {
          id: string | null
          automation_id: string | null
          action_type: unknown | null
          action_config: Json | null
          action_order: number | null
          agent_id: string | null
          mcp_server_id: string | null
          webhook_id: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          automation_id?: string | null
          action_type?: unknown | null
          action_config?: Json | null
          action_order?: number | null
          agent_id?: string | null
          mcp_server_id?: string | null
          webhook_id?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          automation_id?: string | null
          action_type?: unknown | null
          action_config?: Json | null
          action_order?: number | null
          agent_id?: string | null
          mcp_server_id?: string | null
          webhook_id?: string | null
          created_at?: string | null
        }
      }
      bpm_automation_conditions: {
        Row: {
          id: string | null
          automation_id: string | null
          condition_order: number | null
          logic_operator: string | null
          field_id: string | null
          field_path: string | null
          operator: string | null
          compare_value: string | null
          compare_values: Json | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          automation_id?: string | null
          condition_order?: number | null
          logic_operator?: string | null
          field_id?: string | null
          field_path?: string | null
          operator?: string | null
          compare_value?: string | null
          compare_values?: Json | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          automation_id?: string | null
          condition_order?: number | null
          logic_operator?: string | null
          field_id?: string | null
          field_path?: string | null
          operator?: string | null
          compare_value?: string | null
          compare_values?: Json | null
          created_at?: string | null
        }
      }
      bpm_automation_executions: {
        Row: {
          id: string | null
          automation_id: string | null
          card_id: string | null
          trigger_data: Json | null
          status: string | null
          actions_executed: number | null
          actions_total: number | null
          result: Json | null
          error: string | null
          started_at: string | null
          completed_at: string | null
          execution_time_ms: number | null
        }
        Insert: {
          id?: string | null
          automation_id?: string | null
          card_id?: string | null
          trigger_data?: Json | null
          status?: string | null
          actions_executed?: number | null
          actions_total?: number | null
          result?: Json | null
          error?: string | null
          started_at?: string | null
          completed_at?: string | null
          execution_time_ms?: number | null
        }
        Update: {
          id?: string | null
          automation_id?: string | null
          card_id?: string | null
          trigger_data?: Json | null
          status?: string | null
          actions_executed?: number | null
          actions_total?: number | null
          result?: Json | null
          error?: string | null
          started_at?: string | null
          completed_at?: string | null
          execution_time_ms?: number | null
        }
      }
      bpm_automations: {
        Row: {
          id: string | null
          flow_id: string | null
          name: string | null
          description: string | null
          is_active: boolean | null
          trigger_type: unknown | null
          trigger_config: Json | null
          conditions: Json | null
          execution_count: number | null
          last_executed_at: string | null
          created_by: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string | null
          flow_id?: string | null
          name?: string | null
          description?: string | null
          is_active?: boolean | null
          trigger_type?: unknown | null
          trigger_config?: Json | null
          conditions?: Json | null
          execution_count?: number | null
          last_executed_at?: string | null
          created_by?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string | null
          flow_id?: string | null
          name?: string | null
          description?: string | null
          is_active?: boolean | null
          trigger_type?: unknown | null
          trigger_config?: Json | null
          conditions?: Json | null
          execution_count?: number | null
          last_executed_at?: string | null
          created_by?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      bpm_card_answer_fields: {
        Row: {
          id: string | null
          card_answer_id: string | null
          field_id: string | null
          value: string | null
          value_json: Json | null
          value_numeric: number | null
          value_date: string | null
          value_bool: boolean | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string | null
          card_answer_id?: string | null
          field_id?: string | null
          value?: string | null
          value_json?: Json | null
          value_numeric?: number | null
          value_date?: string | null
          value_bool?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string | null
          card_answer_id?: string | null
          field_id?: string | null
          value?: string | null
          value_json?: Json | null
          value_numeric?: number | null
          value_date?: string | null
          value_bool?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      bpm_card_answers: {
        Row: {
          id: string | null
          card_id: string | null
          form_id: string | null
          flow_step_id: string | null
          answered_by: string | null
          created_at: string | null
          updated_at: string | null
          deleted_at: string | null
        }
        Insert: {
          id?: string | null
          card_id?: string | null
          form_id?: string | null
          flow_step_id?: string | null
          answered_by?: string | null
          created_at?: string | null
          updated_at?: string | null
          deleted_at?: string | null
        }
        Update: {
          id?: string | null
          card_id?: string | null
          form_id?: string | null
          flow_step_id?: string | null
          answered_by?: string | null
          created_at?: string | null
          updated_at?: string | null
          deleted_at?: string | null
        }
      }
      bpm_card_attachments: {
        Row: {
          id: string | null
          card_id: string | null
          file_name: string | null
          file_path: string | null
          file_size: number | null
          mime_type: string | null
          uploaded_by: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          card_id?: string | null
          file_name?: string | null
          file_path?: string | null
          file_size?: number | null
          mime_type?: string | null
          uploaded_by?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          card_id?: string | null
          file_name?: string | null
          file_path?: string | null
          file_size?: number | null
          mime_type?: string | null
          uploaded_by?: string | null
          created_at?: string | null
        }
      }
      bpm_card_checklist_items: {
        Row: {
          id: string | null
          checklist_id: string | null
          title: string | null
          is_checked: boolean | null
          sort_order: number | null
          checked_by: string | null
          checked_at: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          checklist_id?: string | null
          title?: string | null
          is_checked?: boolean | null
          sort_order?: number | null
          checked_by?: string | null
          checked_at?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          checklist_id?: string | null
          title?: string | null
          is_checked?: boolean | null
          sort_order?: number | null
          checked_by?: string | null
          checked_at?: string | null
          created_at?: string | null
        }
      }
      bpm_card_checklists: {
        Row: {
          id: string | null
          card_id: string | null
          title: string | null
          sort_order: number | null
          created_by: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          card_id?: string | null
          title?: string | null
          sort_order?: number | null
          created_by?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          card_id?: string | null
          title?: string | null
          sort_order?: number | null
          created_by?: string | null
          created_at?: string | null
        }
      }
      bpm_card_comments: {
        Row: {
          id: string | null
          card_id: string | null
          user_id: string | null
          content: string | null
          content_html: string | null
          mentions: string[] | null
          parent_id: string | null
          created_at: string | null
          updated_at: string | null
          deleted_at: string | null
          search_vector: unknown | null
        }
        Insert: {
          id?: string | null
          card_id?: string | null
          user_id?: string | null
          content?: string | null
          content_html?: string | null
          mentions?: string[] | null
          parent_id?: string | null
          created_at?: string | null
          updated_at?: string | null
          deleted_at?: string | null
          search_vector?: unknown | null
        }
        Update: {
          id?: string | null
          card_id?: string | null
          user_id?: string | null
          content?: string | null
          content_html?: string | null
          mentions?: string[] | null
          parent_id?: string | null
          created_at?: string | null
          updated_at?: string | null
          deleted_at?: string | null
          search_vector?: unknown | null
        }
      }
      bpm_card_email_attachments: {
        Row: {
          id: string | null
          email_id: string | null
          file_name: string | null
          file_path: string | null
          file_size: number | null
          mime_type: string | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          email_id?: string | null
          file_name?: string | null
          file_path?: string | null
          file_size?: number | null
          mime_type?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          email_id?: string | null
          file_name?: string | null
          file_path?: string | null
          file_size?: number | null
          mime_type?: string | null
          created_at?: string | null
        }
      }
      bpm_card_emails: {
        Row: {
          id: string | null
          card_id: string | null
          direction: string | null
          from_address: string | null
          to_addresses: string[] | null
          cc_addresses: string[] | null
          bcc_addresses: string[] | null
          subject: string | null
          body_text: string | null
          body_html: string | null
          message_id: string | null
          in_reply_to: string | null
          has_attachments: boolean | null
          email_config_id: string | null
          sent_by: string | null
          sent_at: string | null
          received_at: string | null
          is_read: boolean | null
          metadata: Json | null
          created_at: string | null
        }
        Insert: {
          id?: string | null
          card_id?: string | null
          direction?: string | null
          from_address?: string | null
          to_addresses?: string[] | null
          cc_addresses?: string[] | null
          bcc_addresses?: string[] | null
          subject?: string | null
          body_text?: string | null
          body_html?: string | null
          message_id?: string | null
          in_reply_to?: string | null
          has_attachments?: boolean | null
          email_config_id?: string | null
          sent_by?: string | null
          sent_at?: string | null
          received_at?: string | null
          is_read?: boolean | null
          metadata?: Json | null
          created_at?: string | null
        }
        Update: {
          id?: string | null
          card_id?: string | null
          direction?: string | null
          from_address?: string | null
          to_addresses?: string[] | null
          cc_addresses?: string[] | null
          bcc_addresses?: string[] | null
          subject?: string | null
          body_text?: string | null
          body_html?: string | null
          message_id?: string | null
          in_reply_to?: string | null
          has_attachments?: boolean | null
          email_config_id?: string | null
          sent_by?: string | null
          sent_at?: string | null
          received_at?: string | null
          is_read?: boolean | null
          metadata?: Json | null
          created_at?: string | null
        }
      }
      bpm_card_labels: {
        Row: {
          card_id: string | null
          label_id: string | null
        }
        Insert: {
          card_id?: string | null
          label_id?: string | null
        }
        Update: {
          card_id?: string | null
          label_id?: string | null
        }
      }
    }
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
    CompositeTypes: Record<string, unknown>
  }
  zapp: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
    CompositeTypes: Record<string, unknown>
  }
  evo: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
    CompositeTypes: Record<string, unknown>
  }
}
