// Generated by supabase_generate_typescript_types
// DO NOT EDIT MANUALLY — regenerate with supabase_generate_typescript_types
// Generated: 2026-07-30T15:15:05.419Z
// NOTE: zapp and evo use structural stubs compatible with schema.ts type helpers.
// TableStub has {Row, Insert, Update, Relationships} — no more 'never' cascade.
// For full per-table type definitions, regenerate via supabase_generate_typescript_types.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

type TableStub = {
  Row: Record<string, unknown>
  Insert: Record<string, unknown>
  Update: Record<string, unknown>
  Relationships: Array<Record<string, unknown>>
}

type ViewStub = {
  Row: Record<string, unknown>
  Relationships: Array<Record<string, unknown>>
}

type FunctionStub = {
  Args: Record<string, unknown>
  Returns: unknown
}

type EnumStub = string

export type Database = {
  public: {
    Tables: { [key: string]: TableStub }
    Views: { [key: string]: ViewStub }
    Functions: { [key: string]: FunctionStub }
    Enums: { [key: string]: EnumStub }
    CompositeTypes: { [key: string]: Record<string, unknown> }
  }
  zapp: {
    Tables: { [key: string]: TableStub }
    Views: { [key: string]: ViewStub }
    Functions: { [key: string]: FunctionStub }
    Enums: { [key: string]: EnumStub }
    CompositeTypes: { [key: string]: Record<string, unknown> }
  }
  evo: {
    Tables: { [key: string]: TableStub }
    Views: { [key: string]: ViewStub }
    Functions: { [key: string]: FunctionStub }
    Enums: { [key: string]: EnumStub }
    CompositeTypes: { [key: string]: Record<string, unknown> }
  }
}
