/** empty-states component for the ui section. */
export {
  EmptyState,
  InboxEmptyState,
  ContactsEmptyState,
  DashboardEmptyState,
  SearchEmptyState,
  NotificationsEmptyState,
  TagsEmptyState,
  CallsEmptyState,
  TranscriptionsEmptyState,
  CampaignsEmptyState,
  ChatbotEmptyState,
  PipelineEmptyState,
  ReportsEmptyState,
  IntegrationsEmptyState,
  TemplatesEmptyState,
  CatalogEmptyState,
  type EmptyStateContext,
} from './UnifiedEmptyState';
